### ISSUE TITLE
Preprocess function broken?

### ISSUE THREAD

**Issue by davidchase** [23/resumable.js#114]
Hi,
I was wondering if the preprocess function is broken because even after I call to the preprocessFinished method on the passed chunk parameter the fileSuccess event and complete events do not trigger...

Unless Im not implementing it correctly

**Comment by thegreenpizza** [comment]
This issue desperately needs to be fixed. I will be issuing a PR today.

**Comment by steffentchr** [comment]
Perfect -- and thanks. The pull request has been merged now.
