### ISSUE TITLE
Nginx errors

### ISSUE THREAD

**Issue by binarykitchen** [23/resumable.js#119]
Hello again

I am getting plenty of nginx errors like these when uploading huge video files:

```
*145 client intended to send too large body: 56755236 bytes
```

The chunk size is set to 5 MB, so this shouldn't happen. Any clues or advice what nginx config I should try?

**Comment by MorosithIi** [comment]
@binarykitchen Could you please post an example of how to use resumable.js with NGINX?

**Comment by binarykitchen** [comment]
Too late, not using resumable.js anymore
