### ISSUE TITLE
Add checksum support

### ISSUE THREAD

**Issue by evanworley** [23/resumable.js#135]
Hi all,

Resumable.js looks great, but based on my reading it doesn't seem to support any checksum (MD5 or like) for verifying the integrity of an upload part. Adding this would ensure the integrity of the uploaded data.

Some useful resources for making this happen
- https://code.google.com/p/crypto-js/
- https://github.com/padolsey/operative

**Comment by sbagri** [comment]
Based on the labels, it looks like this feature will be released in v2. Is there any timeline of when it will be released. Also is there a branch where this feature is already included. In the main branch, I can't see this code.

**Comment by keyscores** [comment]
+1 any updates on incorporating sparkmd5 in here?

**Comment by hyperknot** [comment]
Is there a way to calculate MD5 for the whole file here, which might not even fit in the memory? It'd be great to "prove" that the full chunking - uploading - server side combining process all went right. Individual chunk hashing only proves the uploading went right, with no way to check if the server could combine the files back into the original one.

**Comment by Jasata** [comment]
Am I missing something obvious, or why does it need to be a GET query after POST'ing the chunk? I thought it would be simpler to just include the chunk checksum along with the POST and let the server reply like it always does - just simply do the checksum calculation as well, if the POST has that information.

But like I said - I may be missing something obvious...
