### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by jarodium** [23/resumable.js#136]
I would like to make a local preview of an image when I select one.
Since there is no global var to hold the local path, I would like to know how can I do this.

I'm using the latest Firefox version.

Any way around this?

Thank you in advance.
Kind regards
Pedro

**Comment by trevsny** [comment]
For any one coming across this trying to do an image preview with a Resumable File Object do what 
^^ AidasK wrote and make sure the argument passed to fileReader.readAsDataURL() is the file property of the Resumable File Object.
