### ISSUE TITLE
File changed / MD5 hash?

### ISSUE THREAD

**Issue by osuritz** [23/resumable.js#175]
Hi,

We're considering using this library... but I wanted to know what happens if the original file has changed when the user tries to resume an upload. Is there some hashing going on that can guarantee that we don't resume say part 2 of the new file to part 1 of the original file?

Thanks!

**Comment by keyscores** [comment]
@steffentchr I've seen several issues regarding including checksum in the metadata. Seems like it's a feature you don't want to include. What's the reasoning behind this?

**Comment by steffentchr** [comment]
It's mostly that checksumming needs are pretty varied in terms of computation and external dependencies (including in the server side) -- combined with the fact that we wouldn't use the feature in production ourselves and wouldn't have too much of a footprint with it in practise. Having said this, I've encourage stable and well-tested PRs for the feature and would be happy to accept.
