### ISSUE TITLE
Cancel/Resume individual file upload

### ISSUE THREAD

**Issue by monsieur-ricky** [23/resumable.js#199]
Hi there,

I'm really new to ResumableJS and i'm trying to cancel/resume individual file uploads.
I've successfully managed to upload multiple files in chunks to a server showing the overall progress and individual file upload percentage.
What i would like to know is how can i cancel/abort an individual file upload without interrupting the other file uploads?
Each individual file is displayed with its upload percentage and a cancel button. This is how i'm trying to abort/cancel an individual file:

```
// Handle file add event
r.on('fileAdded', function (file)
{
        // Add the file to the list
        $('.resumable-list').append('<li class="resumable-file-' + file.uniqueIdentifier + '">Uploading <span class="resumable-file-name"></span> <span class="resumable-file-progress"></span> <button type="button" onclick="file.cancel(); return false;">Cancel</button>');
        $('.resumable-file-' + file.uniqueIdentifier + ' .resumable-file-name').html(file.fileName);

        // Actually start the upload
        r.upload();
});
```

How should i accomplish this?
`<button type="button" onclick="file.cancel(); return false;">Cancel</button>`

Thanks in advance :)

**Comment by milad-kh** [comment]
dear @steffentchr 
how about pause and resume an individual file object?
i tested this but not worked
`file.pause();`
pause() only work on whole object not an individual file reference
