### ISSUE TITLE
Uploading stops if file type or size constraints fail

### ISSUE THREAD

**Issue by digitalnature** [23/resumable.js#201]
I'm not sure if this is the intended behavior, it doesn't seem normal to me.

Your `each` function definition suggests that if `false` is returned by the callback function, the loop will break. When you're iterating the fileList if any of these checks fail, `false` is returned. I think you meant :

```
return o.minFileSizeErrorCallback(file, errorCount++);
```

instead of:

```
o.minFileSizeErrorCallback(file, errorCount++);
return false;
```

This way the caller has some control over what happens.
But it would probably be better to ignore files that don't meet the criteria, by using `else if`s

**Comment by Roanvdploeg** [comment]
Hi @steffentchr 

Will you still accept a pull request for this issue?

**Comment by steffentchr** [comment]
Sure.
