### ISSUE TITLE
Resize image before upload

### ISSUE THREAD

**Issue by riaan53** [23/resumable.js#202]
Hi, I need to be able to resize an image before uploading it to the server.

Normally I just load the image onto a canvas, resize it and then canvas.toDataURL("image/png") to get the base64 data of the resized image and then upload it to the server.

Is there a way to access the file data and modify it before resumable.js splits it into chucks or to feed my own file or data into resumable.js? 

This will also be helpful when using the camera plugin in cordova which returns base64/fileuri to get the files into resumable.js

**Comment by riaan53** [comment]
I see I can use the .addFile(file) method and just convert my base64 to a blob and file obj. Will give it a try and let you know the outcome.

**Comment by riaan53** [comment]
I have found a simple solution for image resize/manipulation with resumable.js. Also now you can use resumable.js as is on Cordova as well! See https://github.com/vsivsi/meteor-file-collection/issues/29

**Comment by homerjam** [comment]
[Pertinent part of above](https://github.com/vsivsi/meteor-file-collection/issues/29#issuecomment-70421435)
