### ISSUE TITLE
Ability to start individual ResumableFiles

### ISSUE THREAD

**Issue by tarnfeld** [23/resumable.js#203]
Perhaps this is already possible, but it would be awesome if I could start uploading a file as soon as it was added to the Resumable instance. I still want to support multiple files, so maintaining the state of multiple Resumable instances would be quite painful.

I think this is quite related to #92 as the ability to pause/cancel each file would also be required.

**Comment by steffentchr** [comment]
You should be able to start uploading immediately after the first file is added -- and then further added files will just be managed by the queue. In fact, you can simply call start every time a file is added to get the expected behaviour.

**Comment by tarnfeld** [comment]
That is fantastic, thanks so much for the speedy and helpful reply!!
