### ISSUE TITLE
Where does resumable.js uploads the temporary files, is it possible to specify?

### ISSUE THREAD

**Issue by rodrigomf24** [23/resumable.js#207]
Hi, I'm using resumable.js with Ember.js it works great, the only issue I have is that I don't know where resumable.js saves the temporary files, I assumed it would save them in the temp folder in osx but it doesn't. I'm using Laravel for the backend but it get's the file information through get and not in the _FILES var. I tried looking for info in stackoverflow, google and nothing.

**Comment by steffentchr** [comment]
The temporary folder is controlled by the server-side implementation -- which isn't actually part of Resumable.js itself. We do provide some sample implementations, for example [this one for Node](https://github.com/23/resumable.js/blob/master/samples/Node.js/resumable-node.js) which takes `temporaryFolder` as an argument when the library is inited. In other words: You'll need to have a look at the code being run server-side to figure out this mystery.

Steffen
