### ISSUE TITLE
Add dynamic post params

### ISSUE THREAD

**Issue by sveri** [23/resumable.js#209]
Hi,

Would it be possible to add dynamic parameters when uploading a file?
I thought the query: key would do this on construction of a new Resumable, but I cannot provide a callback.
Whenever I try that I get that function submitted to the server instead of the return value of the function.

**Comment by steffentchr** [comment]
`query` is currently just a flat hash, can you provide an example of how you would want to extend functionality?

Steffen

**Comment by sveri** [comment]
I was thinking about the possibility to add a callback function as a value in that map.
However, I just found out that I can mutate the opts.query map when adding a file, which is sufficient in my case, it just was not obvious to me.
