### ISSUE TITLE
Edit Resumable.query configuration option on Resumable.upload

### ISSUE THREAD

**Issue by jdq22** [23/resumable.js#217]
Hello,

I want to pass along form data with each chunk, but the target and query configuration options are set on page load (from what I understand), as opposed to dynamically. Is it possible for me to edit the query object when I call Resumable.upload?

Here's the code snippet:

var r = new Resumable ({
    target: 'test.php',
    query: {email: document.getElementById('email').value},
});

**Comment by psaxena** [comment]
I had the same problem.

What worked for me is, Just before calling upload i.e. r.upload(), I modified query parameter. You can try below:-

var r = new Resumable({
	target: "somefile.php",
	testChunks : false,
	chunkSize : 1 * 1024 * 1024,
	query : {
		email: "abcd"
	}
});


r.opts.query.email= document.getElementById('email').value;
r.upload();

**Comment by jdq22** [comment]
Thanks, @psaxena. That worked for us!

**Comment by mishra1947** [comment]
I had the same problem.

What worked for me is, i defined query as a function

var r = new Resumable({
        target: "somefile.php",
        testChunks: false,
        chunkSize: 1 * 1024 * 1024,
        query: function () {
            return{
                email: document.getElementById('email').value
            }
        }
    });

r.upload();
