### ISSUE TITLE
Uploading big files causing firefox to crash

### ISSUE THREAD

**Issue by psaxena** [23/resumable.js#220]
I am using resumable js to upload files for my applications. Though maximum file size we support id 2GB.

But what i observed is someone selects big files say 5 files 1.5 GB each, after sometime fireforx crashes and crash report says memory leak. Same works fine for chrome.

**Comment by topgun743** [comment]
I was also having the same issue and my resolve to this is that keep the chunk size not bigger than 10 MB. Chunk size bigger than this does cause issue in Firefox.

**Comment by steffentchr** [comment]
@psaxena What was your chunk size when seeing the problem?

**Comment by topgun743** [comment]
The problem causing chunk size was 50 mb

**Comment by steffentchr** [comment]
Ah okay; weird that this is causing issues, but in either case optimal chunk size is likely much less that 50 MB -- at least considering stability.
