### ISSUE TITLE
the file input shows "no file  chosen",while I chosen a file and can be uploaded in Chrome

### ISSUE THREAD

**Issue by bung87** [23/resumable.js#223]
Chrome Version 39.0.2171.95 (64-bit)

**Comment by dagomar** [comment]
Sadly I am experiencing the same issue :( At least I know I am not the only one. 
I did find the line in which this behaviour is created; it is on line 848 where:

`e.target.value = '';`

When I comment this out it works the way I would like it to, I cannot vouch for any negative side-effects. Perhaps this could be added as a setting?

Sincerely,

Dagomar

**Comment by steffentchr** [comment]
I can only find that code twice in the lib, but neither on line 848:

https://github.com/23/resumable.js/blob/master/resumable.js#L910
https://github.com/23/resumable.js/blob/master/resumable.js#L1004

**Comment by dagomar** [comment]
Sorry I think I was working with an older version of resumable, it is found on line 911. I am creating a pull request now for the change, I have made it into an option. Hold on!

**Comment by dagomar** [comment]
Hm, I didn't notice there is also that on line 1004. However, that is for the dropzone implementation, which probably makes less sence to change? Let me know if I should change it there as well, then I can update the pull request!

**Comment by steffentchr** [comment]
Yeah, it's a good point -- but I'm wondering if there are consequences to doing this. The usual patterns will be that this input isn't displayed at all (at least that's the case in all implementation I've seem of resumable in the wild) and i'm wondering if it can become confusion for the input field to show a subset of selected files (in the cases where people do selects more than once).

**Comment by dagomar** [comment]
I can see your point, and I am also not sure if this could cause any side-effects. In my case (and I am guessing @bung87), I would like to use a default file input, and have it behave like that. In my implementation I would then empty it (or actually hide it) once the upload is completed, then show the uploaded file in a list. Right now I am using it for a single upload, in which case it makes sense, I noticed the behaviour of the multiple file input is to show something like '3 files selected'. In that case I guess it would make more sense to add them to a list and remove them from the input. However, if there are no negative functional side effects to this option, it would be very nice to have as an option at least. I am curious to your thoughts.

And by the way, thank you for an excellent piece of software! Made my life so much easier :)

**Comment by steffentchr** [comment]
It made my life easier as well ;)

Great about the pull request; am merging it now.

**Comment by steffentchr** [comment]
Ah, it wasn't a pull request. If you submit the change as a PR, I'll happily merge.

**Comment by dagomar** [comment]
Hi @steffentchr,
This will be my first pull request on Github, I didn't realise I wasn't creating the request to the right repository :) Should be there now!

Sincerely,

Dagomar

**Comment by steffentchr** [comment]
No problem -- thank you for taking the time!

Steffen

**Comment by dagomar** [comment]
You're welcome!

**Comment by bung87** [comment]
@dagomar it's last year things,I just knew resumable.js and thought use it in my project simply,so I just use the original file input,your suggestion is more modern way,and avoid this problem,I think I will implement it as that way at next version,thank you for you explanation.enjoy coding!

**Comment by BorisMorel** [comment]
Hello,
Here is an amazing article that you may find really useful, olease read it here <http://mestitraxi.whonue.info/xyvhoyy>
Rushing, morel.boris@orange.fr

**Comment by BorisMorel** [comment]
Hey,

What a wonderfull news from our best friend I've just read, you may read it yourself here <http://mentongatry.howardandpilar.com/xyliu>

Thx, morel.boris@orange.fr

**Comment by BorisMorel** [comment]
Hi,
Look what they have for you, I guess it's worth reading, more info here <http://ndezibome.usatop10lists.com/xyldwdf>

morel.boris@orange.fr
