### ISSUE TITLE
Framework doesn't chunk up file upload on 'fileAdded' event

### ISSUE THREAD

**Issue by jmesh** [23/resumable.js#230]
Trying to incorporate resumables js into my application, and after installing the listeners, the file is added to the parent resumables config object, but there are no chunks created when it comes time to upload. Any advice? Am I missing something or do I need to programmatically instantiate the chunking? 

Thanks, 
- J

**Comment by steffentchr** [comment]
Hard to debug based on the description -- do you have a link where this is running?

**Comment by jmesh** [comment]
No...unfortunately the app isn't public yet. I'm just trying to understand how and when the Resumables js library will actually take the resumables file object and chunk it up into the 1 MB chunk size I set for the upload. If you can shed some light on that, I'd be very thankful.
