### ISSUE TITLE
To undo assignDrop or assignBrowse from one of the DOM element

### ISSUE THREAD

**Issue by psaxena** [23/resumable.js#234]
I have list where all the list items are droppables. Now if i want to remove one of  DOM element from resumable objects(Not from HTML page), Is there any way to do it?

**Comment by steffentchr** [comment]
Hi @psaxena 

There's currently no way of undoing `assignBrowse`, but `unAssignDrop()` is available for use in the other case.

For the former though, removing all `<input>` nodes within the objects should do the trick in almost all cases.

Steffen
