### ISSUE TITLE
How to assert that all the files have been uploaded and transfer is completed?

### ISSUE THREAD

**Issue by saipavanvutukuri** [23/resumable.js#240]
Hi,

I am using resumable.js as a part of my task to upload large files.I am using Java in the server side with UploadServlet example. My task is to make a get request to another web app once all the files have been successfully uploaded. My question in this context is how can we confirm that all the files have been uploaded and file transfer is complete. Suppose I am uploading 4 files simultaneously. I want to call another web service when all four files upload has been completed.Can anyone help me with What is the best possible way to accomplish this task in java.Some times the temp files are not getting deleted in the directory though the file is completely uploaded.

**Comment by steffentchr** [comment]
Hi @saipavanvutukuri 

Resumable.js itself doesn't do this, since all uploads are individual -- even if they're handled by the library at the same time. This is also reflected in the fact that you can add more files to the upload queue while the process is ongoing, so the size of the queue is in flush.

When the full queue has been processed and completed though, an event is fired within Resumable -- which in turn can be used for you purpose:

    r.on('complete', function(){
      // Tell the server that all queued files have been delivered
      ....
    });

**Comment by saipavanvutukuri** [comment]
Basing on your comment I tried to do something like this .But this isn't working .I am unable to access isuploadcompleted param on the server side. Please let me know any mistakes I made in this code.

client side
   r.on('complete', function(){
              // Hide pause/resume when the upload has completed
              $('.resumable-progress .progress-resume-link, .resumable-progress .progress-pause-link').hide();
         
//Calling server to say upload has been completed
     
              $.ajax({  
                type: "POST",  
                url: "UploadServlet/Helper",  
                data: "isuploadcompleted="+"true",
                success: function(data) {
    
                                         }
            });         
  });  
          
Server side 
 public void Helper(HttpServletRequest request)
    {
          System.out.println("Param user side"+request.getParameter("isuploadcompleted")); 
    }

**Comment by steffentchr** [comment]
This seems to be a problem related to server-side communication outside of Resumable. Even if I'd love to, I unfortunately cannot help well on such issues.
