### ISSUE TITLE
$.fileObj.file.slice method not supported, IE11 and Chrome 44

### ISSUE THREAD

**Issue by davidpowerkneat** [23/resumable.js#242]
I'm seeing errors in the console when trying to use resumable. See info and output below.

## Info ##
1. Add file to upload
2. start upload
3. no connection made to server
4. error in console, 

### IE11 ###
SCRIPT438: Object doesn't support property or method 'slice'
File: resumable.js, Line: 725, Column: 9

### Chrome Version 44.0.2403.130 m ###
Uncaught TypeError: $.fileObj.file[func] is not a function
File: resumable.js 725

**Comment by steffentchr** [comment]
Thanks @davidpowerkneat -- it certainly does look like an error from Resumable, but I can't seem to reproduce it myself. 

I did some quick checking in both browsers (in Win 8.1) and with the test page from the repository: http://prototypes.labs.23company.com/resumable.js/test.html
Would you mind checking an upload there and copying back contents from the developer console?

**Comment by tylermauthe** [comment]
Any updates on this? I am evaluating this library and browser support is an important consideration.

**Comment by steffentchr** [comment]
We're using the library in production on IE11 ourselves and I haven't seen this issue reproduced or reported elsewhere. Do you have more information and I'd be happy to review?

**Comment by tylermauthe** [comment]
Nope, thanks for the info.

**Comment by davidpowerkneat** [comment]
We used a different library in the end. Thanks for following up.
