### ISSUE TITLE
Filenames with a double period

### ISSUE THREAD

**Issue by nickpeck** [23/resumable.js#243]
We have been using resumable successfully as part of our application and lately encountered some issues with files containing a double period mark before the extension, eg filename..ext

We added the following clause to catch and prevent users submitting files in this manner, where the resumable object has been bound to a DOM element using assignDrop:

	resumable.on('fileAdded', function(file, event){
		
		if(file.fileName.indexOf('..') !== -1) {
			alert('invalid file...')
			return false;
		}
    
		
However, if the user then renames the file, removing the duplicate '.', so it becomes filename.ext and then attempts to add it into our queue, the fileAdded event fails to fire.

**Comment by steffentchr** [comment]
Hi @nickpeck -- is this a problem with Resumable.js or related to something behind the scenes? Because in our own usage of Resumable.js this hasn't come up and I can't force the error with a double-period file name.

**Comment by nickpeck** [comment]
The simplest test case for me that produces this condition is as follows:

	<!DOCTYPE html>
	<html>
		<head></head>
		<body>
			
			<div id="dropbox" style="height:400px;border:1px black dashed;">
							
				Drop files here
					
			</div>

		</body>	
		
		<script type="text/javascript" src="./resumable.js"></script>
		<script type="text/javascript">
		var r = new Resumable();
		r.assignDrop(document.getElementById("dropbox"));
		r.on('fileAdded', function(file, event){
			alert('you dropped a file ' + file.fileName);
		});	
		</script>
	</html>

If I drag filename..ext into the space, the user-defined fileAdded callback is fired (message box is shown).
If I rename the file to filename.ext and drag it into the space, the callback does not fire, although I can see from the debugger that the resumable onDrop handler is invoked (line 187).

**Comment by steffentchr** [comment]
Which browser is this? And does it work when using the browse option instead for drop?

**Comment by nickpeck** [comment]
Hi there, I'm seeing the same behaviour with Firefox 40.0.2 and Chrome 44.0.2403.155

**Comment by steffentchr** [comment]
Only on drop -- or also on browse?

**Comment by nickpeck** [comment]
Apologies, I forgot to test that : yes the same thing seems to happen with an element that has the assignBrowse binding.
