### ISSUE TITLE
Different Checksum from original file and uploaded file

### ISSUE THREAD

**Issue by ChadTaljaardt** [23/resumable.js#244]
Hello.

I have implmeneted this into my website as a means of uploading files, i wanted to check the integrity of the file and therefore i took a checksum before and after the upload and it turned out to be different value's meaning that the file is changed. 

Do you know why this is happening?

Chads-MBP:temp chadtaljaardt$ shasum headstart_chinese_mandarin_ipod.zip
b2de47abaddb1078c71e82c0c72dd5b93b553a40 
Chads-MBP:temp chadtaljaardt$ shasum headstart_chinese_mandarin_ipod.zip 
b99b6c8c72b9d2341e029f891abba159624066c4  

This can be quite a problem for me if the files are being changed.

**Comment by cpnielsen** [comment]
Could you try and upload a text file and set the chunk size very low (something like 512 bytes) and see if there are any obvious breaks, line breaks inserted, etc.?

The library should transmit raw bytes, so it may be an error when re-assembling the pieces.

**Comment by ChadTaljaardt** [comment]
The file i was using when i saw this issue was a zip file of like 500mb

The first test i done i kept the chunk size as default which was (1*1024*1024) and i uploaded a text file of 182kb full of loreum ipsum, both checksums where correct and matched. i then lowered the chunk size to 512 and then uploaded the same file and it ended up completing on the client side but wasnt reassembled on the server side and the file is just split into multiple parts without being reassembled.

**Comment by cpnielsen** [comment]
It might be that you are expecting the last chunk to be the same size as the others (which is most often not the case).

Are you using any of the sample backends or your own code? Is it possible you can share the "file-reassembly" code?

**Comment by ChadTaljaardt** [comment]
Im using Laravel Framework 

The code im using is from another laravel project found here : https://github.com/rajivseelam/laravel-resumable/blob/master/app/controllers/UploadController.php

Here is the specific code tho. 
```PHP
	/**
	 *
	 * Check if all the parts exist, and
	 * gather all the parts of the file together
	 * @param string $dir - the temporary directory holding all the parts of the file
	 * @param string $fileName - the original file name
	 * @param string $chunkSize - each chunk size (in bytes)
	 * @param string $totalSize - original file size (in bytes)
	 */
	function createFileFromChunks($temp_dir, $fileName, $chunkSize, $totalSize) {
	    // count all the parts of this file
		$total_files = 0;
		foreach(scandir($temp_dir) as $file) {
			if (stripos($file, $fileName) !== false) {
				$total_files++;
			}
		}
	    // check that all the parts are present
	    // the size of the last part is between chunkSize and 2*$chunkSize
		if ($total_files * $chunkSize >=  ($totalSize - $chunkSize + 1)) {
	        // create the final destination file
			if (($fp = fopen('public/temp/'.$fileName, 'w')) !== false) {
				for ($i=1; $i<=$total_files; $i++) {
					fwrite($fp, file_get_contents($temp_dir.'/'.$fileName.'.part'.$i));
					$this->_log('writing chunk '.$i);
				}
				fclose($fp);
			} else {
				$this->_log('cannot create the destination file');
				return false;
			}


	        // rename the temporary directory (to avoid access from other
	        // concurrent chunks uploads) and than delete it
			if (rename($temp_dir, $temp_dir.'_UNUSED')) {
				$this->rrmdir($temp_dir.'_UNUSED');
			} else {
				$this->rrmdir($temp_dir);
			}
		}
	}
```

**Comment by cpnielsen** [comment]
The following line is (potentially) wrong:

     if ($total_files * $chunkSize >=  ($totalSize - $chunkSize + 1)) {

Depending on whether `forceChunkSize` is true or false, the last chunk size will either be in the range of `1 - $chunkSize` or `$chunkSize - (2*$chunksize-1)`. This could potentially mean you assemble the file before you have received the last chunk.

A better way would be to just use the `resumableTotalChunks` and compare that to the number of files OR to tally the file sizes of all the chunks and compare it exactly against the `resumableTotalSize`. There is no reason to be "fuzzy" when it comes to determining whether the upload has finished.

In cases where the files are corrupted, could you check the log for the `writing chunk X` statements and see if the number of chunks match the actual total?

**Comment by steffentchr** [comment]
Also, this code only checks that there's a number of files present -- not that all files have been delivered in full (which @cpnielsen also alludes to). The problem is very likely related to chunks being assembled before being fully uploaded.

**Comment by ChadTaljaardt** [comment]
I see, i looked at the sample code in this repositry and it is the same code i am using, if the code im using is problematic, the sample needs updating to working code?

**Comment by steffentchr** [comment]
Good point, although the samples/example are community provided -- and provided mostly as guidance. Will have a look to see if anyone has a better PHP snippet.

**Comment by ChadTaljaardt** [comment]
Where you able to find any better example's?

**Comment by ChadTaljaardt** [comment]
I made a pull request to fix this issue.

**Comment by cpnielsen** [comment]
Hi ChadTaljaardt 

I am not seeing any open pull requests from you - can you link the one have created? We'll be happy to merge any contributions :+1:

**Comment by ChadTaljaardt** [comment]
Hello, probably have something wrong, still learning how to use github.

Here is a image of what i have so far

https://i.imgur.com/oIYhT1C.png

**Comment by ChadTaljaardt** [comment]
Its probably not nearly the best code or anything but i have tested it on my server and im getting the same checksums on both of the file now.

**Comment by cpnielsen** [comment]
Fork this repository, create a new branch with the changes and open a pull request from that - see https://help.github.com/articles/using-pull-requests/.

The changes looks good, I'll be happy to test and merge when it's set up properly via GitHub.

**Comment by ChadTaljaardt** [comment]
Think I have done it this time 

https://github.com/23/resumable.js/pull/247
