### ISSUE TITLE
Upload progress bar and deletion of temp files 

### ISSUE THREAD

**Issue by saipavanvutukuri** [23/resumable.js#245]
Hi Team, 

i have been using resumable.js as  a part of my project . I am having two issues. 

1.Some times even after complete upload of the files, temp files are not being deleted though original files are created. 

2. Secondly , progress bar is not displaying progress correctly and some times rendering progress like 102 % . Also pause and resume  feature is working only one time .After I pause once and resume it, pause  button is not being updated from resume and I am not able to pause the upload once again .

I am using Java working example provided here

**Comment by steffentchr** [comment]
@saipavanvutukuri Thanks for using Resumable.js. The core library is JavaScript and I'm happy to help along on that; unfortunately though I'm not able to debug server-side issues and specifics like handling temp files and storing chunks as in this case. Really am sorry about this, but I wouldn't know where to begin...
