### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by keyboSlice** [23/resumable.js#248]
In the docs it says that support is limited to firefox 4+ / chrome 11+, can anyone advise on an updated compatibility?

Looking at Caniuse.com it would suggest that it's fine to use everywhere except opera mini and IE < 10, which I'm fine with, if anyone can confirm please?

**Comment by steffentchr** [comment]
We use it for IE11 upwards along with recent versions of Opera.

**Comment by steffentchr** [comment]
From the readme:

> ... support is widely available in to Firefox 4+, Chrome 11+, Safari 6+ and Internet Explorer 10+.

**Comment by keyboSlice** [comment]
Apologies, missed that I was just looking at the docs on the site, thanks

**Comment by steffentchr** [comment]
Yeah, sorry about that -- the site is actually just the README, but needs to be manually updated. Which hasn't happened in a while ;)
