### ISSUE TITLE
Ruby on Rails sample code does not work properly

### ISSUE THREAD

**Issue by hamadata** [23/resumable.js#249]
https://github.com/23/resumable.js/blob/master/samples/Backend%20on%20Ruby%20On%20Rails.md

This sample code judges if all files chunks are uploaded as shown below.
```
currentSize = params[:resumableChunkNumber].to_i * params[:resumableChunkSize].to_i
filesize = params[:resumableTotalSize].to_i

#When all chunks are uploaded
if (currentSize + params[:resumableCurrentChunkSize].to_i) >= filesize
```
This code expects the last upload file chunk is the the last partial file, but in my environment(OSX Chrome,) this expectation is not guaranteed and causes file missing error. 

For my case, counting the uploaded files in the directory fix this problem. 
```
 if Dir.glob("#{dir}/*part*").size == params[:resumableTotalChunks].to_i
```

Does anyone encounter this problem?

**Comment by rvillas** [comment]
+1

**Comment by SubhaPrince** [comment]
Same Problem i am also fetching when internet is disconnected mode than 2min that time no such file or directory for some part missing error is coming
