### ISSUE TITLE
'assignBrowse' listener does not work in IE 11 'edge' mode.

### ISSUE THREAD

**Issue by jmesh** [23/resumable.js#253]
Event listener fires and doesn't error out, but when user adds file to control, no file name added and no file detected when 'fileAdded' event fires which causes an error to be thrown. Works fine on IE 10.

**Comment by steffentchr** [comment]
@jmesh Can you provide a test link for this issue -- just did a bit of testing myself and couldn't reproduce?

**Comment by jmesh** [comment]
No sites up that are public facing for demo.

The following code (line 909 in resumables.js) was the problem and we
removed it:

e.target.value = '';

Project is up and running now.

On Mon, Nov 2, 2015 at 6:38 PM, Steffen Tiedemann Christensen <
notifications@github.com> wrote:

> @jmesh <https://github.com/jmesh> Can you provide a test link for this
> issue -- just did a bit of testing myself and couldn't reproduce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/23/resumable.js/issues/253#issuecomment-153193768>.
>



-- 
Joe Moschler
