### ISSUE TITLE
Error status codes cluttering Browser console. Any other solution?

### ISSUE THREAD

**Issue by topgun743** [23/resumable.js#256]
When testing whether a chunk has been uploaded, I have to return HttpStatusCode > 400 etc., in case if the chunk has already been uploaded to server. But this causes my Browser console to have lots of red messages showing request failures.
 I am wondering if there is any other way of achieving the same purpose I.e aborting chunk file object on client when such red flag comes from server in response code. 

Can I use any other HttpStatusCode that prevents those red messages in Browser console and rather shows regular messages in console?

**Comment by steffentchr** [comment]
Have a look at #127 for background, but essentially you can send back any status code from you server and add that to the `permanentErrors` array. My suggestion would be `204 No Content`.

**Comment by topgun743** [comment]
OK. Thanks for replying. I will check it and tell you the feedback.
