### ISSUE TITLE
How to identify which button that's been clicked that involved the upload?

### ISSUE THREAD

**Issue by shawhu** [23/resumable.js#265]
I don't know if this has been discussed, if it was, please point me to the right direction.

The idea is we now try to use this library because it can resume. And the way to use it, is that imagine we have a bunch of boxes, for drop a file to start uploading.

Now we need to display progress bar on each of those boxes, so we need to know the relation between boxes and uploading files. Is there a proper way to do it? The best place I can think of is by using the R.On() function where when FileAdded, maybe you can return DOM object too? That means when do assignDrop, the resumable.js will keep the DOM object so it can be returned later.

OR, if there is a proper way to do it, please tell me. Thanks!!

**Comment by steffentchr** [comment]
Hi @shawhu -- the use case here is out of scope for Resumable.js proper; it adds a significant amount on complexity to the library to consider different dropzones with different timelines etc. Considering the low footprint of setting up a new Resumable instance, I would simply do so for each dropzone and then write the wrapper to manage the pool around the library.
