### ISSUE TITLE
It doesn't resume the uploads across different sessions?

### ISSUE THREAD

**Issue by sam1111** [23/resumable.js#267]
Hi, I was trying it and noticed that it doesn't resume the uploads across sessions i.e. if i refresh the browser/close the browser and select the same file again upload is started from point blank. Is the functionality not there or do I need to configure something for this to work?

**Comment by steffentchr** [comment]
@sam1111 If the server supports of library's resumable chunk scheme, uploads will catch up from session to session. In the next session, the library with ask the server whether individual chunks are already in place and thus shouldn't be uploaded. The consequence is that uploading starts from 0%, but catches up quickly to the point where the process was stopped -- without uploading any data to achieve this.

**Comment by sam1111** [comment]
@steffentchr does the example provided in samples for node.js doesn't support this at server end? Because I was running that and found out that after a reload every chunk from first to last was uploaded again. Please correct me if I am wrong.

**Comment by steffentchr** [comment]
The [sample code](https://github.com/23/resumable.js/blob/master/samples/Node.js/resumable-node.js) seems to do writing and checking from the local store -- you may want to debug your code to ensure that...

* files are being written to disk
* file checks against those filenames/chunks actually find those files.

**Comment by sam1111** [comment]
Yeah Thanks!!! I realized that after writing the question. My bad!!
