### ISSUE TITLE
beforeCancel event

### ISSUE THREAD

**Issue by RenzoF** [23/resumable.js#268]
When listening for a cancel event the files object is empty.
I have added a new event for beforeCancel which fires on the cancel event before emptying the files array.

This is specially useful for telling the server and this files have are being cancelled and get a proper clean up.

The changes  for this are here
https://github.com/RenzoF/resumable.js/commit/c360cc799883a5284ed1077a66c4cb90b3092a73#diff-03bcb23354a37cce7d530235a3dbbde9

Anyone else doing anything similar found another way to do this ?

**Comment by steffentchr** [comment]
That's a great point -- and a great idea for the cleanup bit (even if you probably need to trigger cleanup on the server in other ways as well). Do you want to contribute with a pull request -- or should I simply add it in?

Steffen

**Comment by RenzoF** [comment]
Thanks @steffentchr just created a pull request, also modified the readme.

Cheers

Renzo
