### ISSUE TITLE
 Extra data to be on the resumable file object

### ISSUE THREAD

**Issue by singlecheeze** [23/resumable.js#274]
Please see the thread here:
https://github.com/crossbario/crossbar/issues/505#issuecomment-159025794

Would it be possible to get extra data added to the file object, similar to how it is included on the resumable object in the query field (please see below).

```js
r = new Resumable({
            target: 'upload',
            chunkSize: 1024 * 512, // Deault 1MB 1024 * 1024
            forceChunkSize: true, // https://github.com/23/resumable.js/issues/51
            simultaneousUploads: 4,
            testChunks: true,
            query: {
                on_progress: 'mono.upload.on_progress',
                session: sess.id //, 
                // ****************** Below in the fileAdded event I will adjust query opts
                //chunk_extra: JSON.stringify({
                //    SR: currentSR,
                //    extra_info2: "blah"
                //}),
                //finish_extra: JSON.stringify({
                //    SR: currentSR,
                //    extra_info2: "blah"
                //})
            }
        });

r.on('fileAdded', function (file) {
                if (currentSR) {
                    //Set file SR to current SR so that if user browses to new SR
                    //file will still be uploaded correctly under it's cached SR
                    file.resumableObj.opts.query.finish_extra = JSON.stringify({
                        SR: currentSR,
                        extra_info2: "blah"
                    });
                    //Need to be able to do this as changing the resumableObj query opts changes it for every file being uploaded, even the file that is currently uploading.
                   //This finish_extra needs to persist so that when file upload completes it gets handed to the on_progress event on the server (or whomever is listening) and could also be read on the client in the resumable event fileProgress and fileSuccess
                   file.finish_extra = JSON.stringify({
                        SR: currentSR,
                        extra_info2: "blah"
                    });

                    r.upload();
                } else {
                    console.log("No SR Selected!");
                }
            });
```

**Comment by steffentchr** [comment]
Hi @singlecheeze 

I tried to follow the referenced issues, but I may have missing something: Are you looking to add per-file properties to be forwarded with queries for that specific file?

Without having actually tested, I'm pretty sure you can achieve this by having `query` be a function:

    var resumableQuery = {
        on_progress: 'mono.upload.on_progress',
        session: sess.id
    }
    r = new Resumable({
        target: 'upload',
        chunkSize: 1024 * 512,
        forceChunkSize: true,
        simultaneousUploads: 4,
        testChunks: true,
        query: function(file){
            return jQuery.extend({}, resumableQuery, file.query);   // this can be improved
        }
    });
    r.on('fileAdded', function (file) {
        file.query {
            finish_extra: JSON.stringify({
                SR: currentSR,
                extra_info2: "blah"
            });
        }
    });

**Comment by markope** [comment]
Did you check it out? 
The fileupload takes whatever chunk_extra or finish_extra values are posted per chunk and reflects this in the WAMP event. So there should be no change needed in crossbar here.
