### ISSUE TITLE
Get server-response in error-event?

### ISSUE THREAD

**Issue by SimonSiefert** [23/resumable.js#275]
Hi!

Is there any way to get the response from the server in case of an error during the upload?

**Comment by steffentchr** [comment]
Sure, the `message` variable in the error callback returns the response text from the server. Something like this will work:

    r.on('fileError', function(file, message){
      alert(message);
    });

This requires that you're sending information back with the 404/500 response from the server.
See also https://github.com/23/resumable.js/blob/master/resumable.js#L799-L801
