### ISSUE TITLE
maxFileSize，fileType

### ISSUE THREAD

**Issue by venture758** [23/resumable.js#276]
These two properties do not take effect，why???

**Comment by steffentchr** [comment]
Test link, details?

**Comment by venture758** [comment]
local java demo

  var r = new Resumable({
            target:'/java-example/upload',
            chunkSize:1*1024*1024,
            simultaneousUploads:1,
            testChunks: false,
            throttleProgressCallbacks:1,
            fileType: ["jpg"],
            maxFileSize: 2*1024*1024,
            method: "octet"
            //  method: 'multipart'
          });

**Comment by steffentchr** [comment]
Alright, without being able to access a concrete demo it's hard to help along. I have verified that both properties are working on my own production systems with Resumable.
