### ISSUE TITLE
Add support multi point upload

### ISSUE THREAD

**Issue by moostad** [23/resumable.js#279]
It would be great if you could add support resumable to upload in different times/browsers. for example: 

1. resumable send hash and size of file to the server.
2. server check if it has partial(s) of file, if so respond for the (random) reminded chunk that needed to upload
3. resumable send the chunk to the server and ask for next chunk from server and so on. 

In this scenario one huge file can be uploaded from different connections  and reduce upload time or  it will be possible to finish upload in several alternative times.

**Comment by steffentchr** [comment]
Pretty sure you can do that right now -- provided that the file name and file size is the same on all connections.
