### ISSUE TITLE
HTTP 204 should signify a successful chunk upload

### ISSUE THREAD

**Issue by atrauzzi** [23/resumable.js#280]
As per [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success):

![image](https://cloud.githubusercontent.com/assets/115199/12937529/3b98dad0-cf6f-11e5-9539-cd870d628542.png)

204 is used when the request succeeded, but the server doesn't have anything to say in response.  Perfect for chunking where every chunk doesn't necessarily merit a response *body*.

**Comment by steffentchr** [comment]
Yup, I think this is addressed in the README -- and discussed here: https://github.com/23/resumable.js/issues/160

**Comment by atrauzzi** [comment]
Does the library currently accept 204?

**Comment by steffentchr** [comment]
Was just looking at that, and I actually don't know why the code wasn't updated to reflect the recommendation -- I have done so now.

**Comment by atrauzzi** [comment]
Awesome.  Sorry, I had seen the discussion and gave the code a glance but couldn't see anything that sniffed out 204, which is why I asked.

Glad I did! :)
