### ISSUE TITLE
204 return on testChunks

### ISSUE THREAD

**Issue by pmenzel** [23/resumable.js#282]
After commit 

The README [says](https://github.com/23/resumable.js#handling-get-or-test-requests) to return a HTTP code 204 for the testChunks GET requests when the chunk is not available on the server yet.
However, [commit 8242cc862a](https://github.com/23/resumable.js/commit/8242cc862abb38f9246a72fc61515d9f7d2e6672) uses 204 as a success code in the test request.

Which status code should now be used for indicating a missing chunk on the server?
Probably the README needs to be updated too.

**Comment by guzmanfg** [comment]
+1

**Comment by steffentchr** [comment]
I guess technically the two could co-exist -- but you're absolutely right that its a very bad idea to do so. Bad judgement on my part and rolled back. Thanks you for bring this up.
