### ISSUE TITLE
upload file using node.js as the client

### ISSUE THREAD

**Issue by drahgon55** [23/resumable.js#284]
I would like to use resumable.js in node.js to run some unit tests. Is there a way to upload a file using node.js as the client. I see that resumable checks to see what environment it is in browser or node.js and exposes itself accordingly. I am confused though as to how I would add a file since I cannot use the assignDrop and assignBrowse function in node.js

**Comment by steffentchr** [comment]
@drahgon55 -- the library itself is set up to using the browser DOM and the HTML5 File API. I guess that you can technically [emulate the latter](https://www.npmjs.com/package/file-api) in Node -- and then not test `assignDrop` and `assignBrowse`, but the test coverage would be limited in that case.
