### ISSUE TITLE
Vague problem while uploading larger files

### ISSUE THREAD

**Issue by dagomar** [23/resumable.js#287]
Hi,

I'm sorry in advance for the vague description of the problem I'm having. I am posting here in the hopes of getting some feedback or pointers how I can debug my problem. 

I have integrated resumable.js in a Drupal 8 site. Locally everything works beautifully. On the server though, I have a very strange problem. When I upload files larger than approximately 9 mb, my entity does not save. Meaning, the upload works, I can see the files in my temp folder, but when I press save, somehow it does not want to save the page, it looks like it does a reload, it goes back to a blank 'add page'. Some things I am going to research:

- My local development environment works, so could it be that there is some server configuration that is needed?
- I checked if the duration of the upload is somehow conflicting by mimicking a slow upload on my local machine (to no avail), perhaps there is a connection reset or something on the live server? How can I test this :s

I understand this is a rather vague question (very specific), and if it's out of place here I apologize. However, if someone has any thoughts, I would greatly appreciate it!

Sincerely,

Dagomar

**Comment by dagomar** [comment]
So... I have fixed it! It turns out that the file input element I was using was actually being uploaded to the server. This caused a sort of timeout that caused the redirect back to the form. I cleared the value of the file input after the upload with resumable is done, and that fixes my problem. So, not an issue with resumable after all! I close this now :)

**Comment by steffentchr** [comment]
That makes sense -- thanks for updating here, because I couldn't really figure out a good reason why this would be failing.

**Comment by luxio** [comment]
@dagomar How do you have integrated resumable.js in Drupal 8? Have you written a module?
