### ISSUE TITLE
What if I want to bind different parameters to each single file when doing a batch upload?

### ISSUE THREAD

**Issue by ylgu** [23/resumable.js#289]

**Comment by steffentchr** [comment]
Use a `function(){...}` for the `query` option.

**Comment by ylgu** [comment]
```function(){...}```? Can be more details, for example I want to bind a file's MD5 to it's self ,how to write my query function? Thanks very mush.

**Comment by steffentchr** [comment]
The function takes two parameters:

    query: function(resumableFile, resumable) {
      return {
        md5: calcMD5(resumableFile)
      };
   }

This means that you'll have raw access to the file in order to do any computation needed.

**Comment by ylgu** [comment]
yeah, this is good for me , thank you very much!
Below is a part of my code:
```
opts.query = function(resumableFile){
                    return angular.extend(scope.queryData,resumableFile.query);
                };
file.query.md5=getMd5(resumableFile);
```
