### ISSUE TITLE
fileNameParameterName typo

### ISSUE THREAD

**Issue by HardlyMirage** [23/resumable.js#295]
https://github.com/23/resumable.js/blob/master/resumable.js#L727

`query[$.getOpt('filenameParameterName')] = $.fileObj.fileName;`

should be:

``query[$.getOpt('fileNameParameterName')] = $.fileObj.fileName;``

Due to this, the `resumableFilename` is not being sent in the POST request

**Comment by steffentchr** [comment]
Fixed now. Really sorry for the regression in #292. It was certainly merged to optimistically on my part, won't happen again!

**Comment by guzmanfg** [comment]
My fault. Sorry
