### ISSUE TITLE
no out-of-the-box working example

### ISSUE THREAD

**Issue by TheTesla** [23/resumable.js#298]
The Node.js version does not work that way:
node app.js 
is wrong. It must be
nodejs app.js
But there is no directory containing the uploaded files. Where are the files dropped?

**Comment by steffentchr** [comment]
The sample itself write to `/tmp/resumable.js/` and the node binary is called `node` on unix systems at least?

**Comment by TheTesla** [comment]
No, the binary is /usr/bin/nodejs, but on some systems there is a softlink node to it. Unfortunatelly on Ubuntu 14.04 systems there may appear a /usr/sbin/ax25-node with node as softlink to it. So it is better to use nodejs instead of node.
