### ISSUE TITLE
Not working with Node 6.0.0

### ISSUE THREAD

**Issue by ShotaMegre** [23/resumable.js#305]
Resumable crashes with Node 6.0.0

**Comment by cpnielsen** [comment]
The node.js sample is fairly old (dating back to 0.10), so I am not entirely surprised it crashes. Could you provide the crash dump and/or errors?

**Comment by cpnielsen** [comment]
I installed a fresh install and experienced an error when uploading. It has been fixed in the latest commit and should be working as expected now (check updated README.md / app.js for instructions on enabling CORS).
