### ISSUE TITLE
The complete event is fired twice when uploading duplicate

### ISSUE THREAD

**Issue by nickdatum** [23/resumable.js#308]
When uploading a file, then trying to upload the same file again, it doesn't upload (which is to be expected), however the "complete" event is fired 3 times (I'm guessing once for every number of simultaneous uploads specified in config).

**Comment by steffentchr** [comment]
Is this after reloading the page/resumable? Or before, because I can't seem to reproduce this one.

**Comment by nickdatum** [comment]
No reloading of the page or resumable in between uploads, literally just uploading one file and then uploading the same file again

**Comment by steffentchr** [comment]
Is there any network traffic happening? Because you shouldn't even be able to add the same file twice to begin with...

Also, are you getting duplicates of the same file in the `filesAdded` event?

**Comment by nickdatum** [comment]
No network traffic happening on the second upload. Basically, it doesn't upload on the second attempt (which is expected behaviour) but it still fires the complete event anyway, 3 times

**Comment by steffentchr** [comment]
But what happens on `fileAdded` -- is that fired with content?

(Otherwise, I think it's simply an over-communication of the fact that the upload IS done. You'll see the `complete` event trigger a few times depending on flow and how many times files are added in either case.)

**Comment by nickdatum** [comment]
Ok, so I've created a jsFiddle here: https://jsfiddle.net/w5zp6cqL/10/
Although it won't work as /upload would need changing to a working path for uploading! Here's what basically happens if I do the following:

1. I click the upload button and select a file (e.g. readme.txt)

It alerts saying "file added" and then alerts saying "complete" (and uploads the file)

2. I click the upload button and select the same file (readme.txt)

It alerts saying "file added" and then alerts **3 times** saying "complete" (although no upload is performed this time)

Does this make sense? Sorry if I'm wording it a bit confusingly.

**Comment by steffentchr** [comment]
Can you try updating with something in this vein, just to see if that improves things:

```uploader.on('filesAdded', function(files) {
  alert('file added');
  if(files.length>0) uploader.upload();
});
```

**Comment by nickdatum** [comment]
This does the trick, thank you. I wonder if the filesAdded event should fire from the code in the first place, if no files? I'll leave that choice to you to make!

**Comment by steffentchr** [comment]
There's a recent ticket on the same issues [here](https://github.com/23/resumable.js/issues/307). I like the idea of firing the event since it makes it explicit that there was user interaction -- but could go either way, I agree.

**Comment by saiballo** [comment]
I have similar issue... 

this code: 

 "if(files.length>0) uploader.upload();" 

resolves the problem if the user does not leave the page.

But if the user reload the page and tries to upload again a file with the same name, page refresh at the end of upload. Why? I don't understand.
