### ISSUE TITLE
How to handle errors during chunking?

### ISSUE THREAD

**Issue by georaldc** [23/resumable.js#320]
How does one handle or catch actual errors that may happen while chunks are being checked/tested? My code that handles uploads falls inside functions that check whether the user is authenticated or not. If an unauthenticated user tries to upload a file (login session expired for example), I just end up with several 302 redirects to my login page, one for every chunk check attempt. Is there a way to stop the whole upload process when this happens, so that I can give feedback to the user?

**Comment by steffentchr** [comment]
You should be able to bind to the error event and cancel the upload process from there?
