### ISSUE TITLE
[Question] Is it possible to use Resumable.js to upload Javascript-generated Files or Blobs?

### ISSUE THREAD

**Issue by snajjar** [23/resumable.js#323]
The question basically says it all.

Resumable.js takes a few div references as a parameter, to handle file upload and interface nicely. But there are many use cases where the developper need to work on the files before upload, or even generate the files to be uploaded (that's mine).

Is there a way to use Resumable.js upload fault-tolence without dealing with fileinput divs?

**Comment by ashudson23** [comment]
```
var r = new Resumable({
 ...
});
r.on('fileAdded', function(file, event){
    r.upload();
});

**r.addFile(BLOBHERE);**
```

**Comment by snajjar** [comment]
Thank you !
