### ISSUE TITLE
Guidelines for how to handle chunks with load balancer

### ISSUE THREAD

**Issue by sachinwalia2k8** [23/resumable.js#325]
I understand this is not a resumable.js issue per se and that's why I mentioned guidelines how people address this in load balancer environment.

Typically any web application will be running at least two instances so in this case it is highly possible that individual chunks will end up in different instances. 

How everybody is addressing this? With distributed object storage it is possible to solve but I am wondering if there are some other ways people are addressing this problem.

**Comment by ettoredn** [comment]
Network/cluster filesystem or the likes (e.g. object stores) is the solution I adopted.

**Comment by steffentchr** [comment]
@sachinwalia2k8 Yeah, that description holds for us as well: We're running multiple web frontends, which resumable chunks being uploaded to any and all of them. Behind the scenes all web servers share some storage (via NFS) and chunks are stored and concatenated there.

**Comment by sosojustdo** [comment]
@steffentchr ,@sachinwalia2k8  iphash with load balancer?
