### ISSUE TITLE
Delay start upload when, I try upload second large file

### ISSUE THREAD

**Issue by khmukid** [23/resumable.js#326]
I am using resumable.js for large file upload with concurrent support. But I am facing an issue when I upload second large file. First file start upload quickly and show progress as accepted but when I upload second file it took more than 1min to show progress and start upload.
I hope you guys help to get rid off from this issue.

Thanks
Mukid

**Comment by steffentchr** [comment]
Is the problem that the file isn't uploading for this time? Or that there's no status for the upload happening? 

Is there a place when I can test this in practise?

**Comment by khmukid** [comment]
Hi, Thanks for reply.
file start upload after 1min+ with progress and it's complete upload successfully. My problem is it's not starting upload instantly after add file and calling "upload()", it take much time to start upload and show progress for second file. I use resumable.js for concurrent upload.

And sorry i can't give you any access on my application, cause it's high level business application.

**Comment by steffentchr** [comment]
Without access I won't be able to help much. Generally, note that Resumable won't actually upload many files at the same time -- rather, it will upload many chunks at the same time. This means that a second file won't start uploading before the former is almost done (the exception to this is `prioritizeFirstAndLastChunk` as described in the docs).
