### ISSUE TITLE
Sample of using resumable.js for uploading multiple concurrent files.

### ISSUE THREAD

**Issue by jimski777** [23/resumable.js#331]
Is there any example how to use resumable.js to make concurrent uploads. What I mean is uploading for example three separate files with different file names in the same time.

I implemented resumable.js and it works well but while one file is uploading all other files are waiting until the first one finishes.

**Comment by HardlyMirage** [comment]
There's a `simultaneousUploads` option you can use

**Comment by jimski777** [comment]
Could you be so kind and provide a short example how to use it.

**Comment by HardlyMirage** [comment]
Show me how you're initializing the resumable object

**Comment by jimski777** [comment]
<script language="JavaScript">
function checkNextStep()
	{
	$("[id^=uploadmsg]").html('');
				
	$('.browsebutton:visible').each(function(index) {
		//debugger;
		$('#uploadmsg'+this.id.replace('browsebutton','')).html('<?php print $ERRORS['invalid-filename']; ?>');
	});
				
	if(r.support)
		{		
		if($('.browsebutton:visible').length>0)
			{
				alert('You must upload promo file for each track.');
				return false;
			}
			
		if(r.isUploading())
			{
				alert('Media files are uploading right now. Please don\'t leave this page until uploading is finished.');
				return false;
			}
		}
		return true;
	}	 
	
	 var r;
	 
	 function reupload(containerId)
	 {
	 	r.removeAllFiles();
		$('#browsebutton'+containerId).show();
		$('#uploadingtxt'+containerId).hide();
		$('#process'+containerId).html('');		
	 }	
	 

	 
$(function() {

if (typeof Resumable == 'undefined') 
	{
		r = new Object();
		r.support = false;
	} 
else
	{
		r = new Resumable({
		  target:'upload_receiver-promo.php',
		  maxFiles: 1,
		  simultaneousUploads: 5,
		  maxFileSize: <?php print constant("MAX_SIZE_MEDIA"); ?>,
		  fileType: ['<?php print implode("','",GetCategoryPromoFileTypes($category)); ?>']
		});
	}

$('.browsebutton').each(function(index) {	
	if(r.support)
		{
			r.assignBrowse(this);
			r.assignDrop(this);
		}
	});
  
//r.assignBrowse(document.getElementById('browseButton0'));

	if(r.support)
	{
	
		r.on('fileAdded', function(file, event){
			//debugger;
			$("[id^=uploadmsg]").html('');
			
			var srcElement = event.srcElement || event.target;
			file.container = srcElement.id.replace('input_','').replace('browsebutton','');
			file.opts = {tid: file.container};
			$('#browsebutton'+file.container).hide().after('<span id="uploadingtxt'+file.container+'">uploading ' + file.fileName + '...</span>');
			
			r.upload();
			//console.debug(file, event);
		  });
		  
		r.on('fileSuccess', function(file){
			//debugger;
			$('#process'+file.container).html('Done &nbsp;&nbsp;(<a onclick="reupload('+file.container+');" style="cursor: pointer; text-decoration: none;" >Reupload?</a>)');
		  });
		  
		r.on('fileProgress', function(file){
			//debugger;
			var progress = Math.floor(file.progress() * 100);
			if(progress == 100)
				progress = 99;			
			$('#process'+file.container).text(progress+'%');
			//document.getElementById('dropField').innerHTML = progress;
			//console.debug(file);
		  });
		  


	 }
	 else
	 {
		alert('browser is not supported');
		/*		$('table').hide();
				$('.panel').hide();
	 			$('#workaround').html('<p><span style="color: red;"><strong>We are sorry but to access this page you need a \
				new version of browser.</strong></span></p><p>Please update your browser or download the latest Firefox, Chrome \
				or Internet Explorer.</p> \
				<ul><li><img src="/img/fav-firefox.gif"><a href="http://www.mozilla.org/firefox/" target=_blank>Download Mozilla Firefox</a></li> \
				<li><img src="/img/fav-chrome.gif"><a href="http://www.google.com/chrome/" target=_blank>Download Google Chrome</a></li>\
				<li><img src="/img/fav-ie.gif"><a href="http://www.microsoft.com/windows/internet-explorer/" target=_blank>Download Internet Explorer</a></li>\
				<li><img src="/img/fav-opera.gif"><a href="http://www.opera.com/" target=_blank>Download Opera</a></li>\
				</ul>');*/
	 }
 
  });	 
	 
	 </script>

**Comment by HardlyMirage** [comment]
Looks like you already have `simultaneousUploads` set to 5, but looking at resumable's code, that only controls the chunks being uploaded, not the file containers. I don't see a way to do this directly. You'll likely need to maintain as many resumable instances as you need files uploaded in parallel.

**Comment by jimski777** [comment]
Without paying any attention to my code, can you provide an example.

**Comment by HardlyMirage** [comment]
You have this code:

	r = new Resumable({
      target:'upload_receiver-promo.php',
      maxFiles: 1,
      simultaneousUploads: 5,
      maxFileSize: <?php print constant("MAX_SIZE_MEDIA"); ?>,
      fileType: ['<?php print implode("','",GetCategoryPromoFileTypes($category)); ?>']
    });

You essentially need to instantiate and maintain 5 of those variables / instances. I suggest maintaining them in an object or array.

	var resumables = [];
	for ( var i = 0; i < 5; i++ ) {
		var r = new Resumable({
	      target:'upload_receiver-promo.php',
	      maxFiles: 1,
	      simultaneousUploads: 5,
	      maxFileSize: <?php print constant("MAX_SIZE_MEDIA"); ?>,
	      fileType: ['<?php print implode("','",GetCategoryPromoFileTypes($category)); ?>']
	    });
	    resumables.push(r)
	}

Things will get complicated when handling events. Your code is messed up enough as is. I suggest you try and understand what you're doing instead of copying-pasting from various sources.

**Comment by jimski777** [comment]
Ok, now I understand. Thank you very much.

**Comment by jimski777** [comment]
Would you be so king to tell me how is my code messed up.

**Comment by steffentchr** [comment]
Hey guys, just chiming in here quickly -- and there's also another thread/issue covering this exact same question elsewhere.

Resumable.js is set up to manage uploads of multiple chunks of files, since this will heavily optimize the use of bandwidth. For example you can run five upload processes at the same time, each uploading a one megabyte chunk of data. Each of these chunks can fail resiliently, and they can conclude asynchronously etc etc. 

This is different from uploading multiple files at the same time, and I consider it bad practise to try to do this -- because if Resumable is set up correctly, you're maxing out the upload capacity already with the chunked uploads; and effectively you would just be upload each file slower if you run file uploads in parallel. The would cannibalise from each other, and certainly in the setup with multiple resumable instances at once managing each of these would make for poorer performance.

**Comment by jimski777** [comment]
Thank for the input steffentchr. Your comments make perfect sense.

**Comment by henno** [comment]
My client wants to select 40 files and upload them in one go. Currently he has to either compress the files beforehand into one zip or upload files one at ta time (40 times). He doesn't want to compress because he thinks it would be easier for his customers if they don't have to do the zipping before uploading. So will I have to find a replacement for ResumableJS  or can it do it?

**Comment by cpnielsen** [comment]
@henno You can easily add 40 files at once, or add one at a time to the same Resumable instance, and it will start from the first file and continue to the last one until finished.

Please refer to the documentation and discussion on this and other issues, and refrain from commenting on old (closed) issues.

**Comment by pacificsoftdevld** [comment]
I have a sane problem likw @henno.
@cpnielsen can you show me an example to solve this problem?
Thanks!!!

**Comment by cpnielsen** [comment]
To both of you, there is no obstacles to overcome - as long as you don't have `maxFiles` set (defaults to un-set), you simply add all the files (drag-and-drop, choose via file open dialog, etc.) and the files will be transferred one after the other, with `simultaneousUploads` number of chunks (not files) being uploaded at a time (see steffentchr's comment earlier).

If you want to identify all the files as belonging to "one" session, you can generate a unique ID and pass it along to the `query` parameter when creating the Resumable.js instance, and it will be sent along with all chunks for all the files. The backend then needs to be able to recognize them and "group" them together again, but that is not something resumable.js can solve for you.
