### ISSUE TITLE
iOS 10.1 beta problems

### ISSUE THREAD

**Issue by Marthyn** [23/resumable.js#336]
Hi, i've been using resumablejs for a video uploading platform for over a year now, works amazing so props for that.

My client started testing with the new iOS beta but the file won't upload, in one case they got the following error message 
![image](https://cloud.githubusercontent.com/assets/642544/19547211/596b727c-9696-11e6-9d75-8e5dcfedf8ba.png)

I will try today to get a javascript log, but i just wanted to see if maybe more people are experiencing problems with the new iOS. It should be released soon

**Comment by steffentchr** [comment]
Hi @Marthyn 

I just upgraded to the most recent iOS 10.1 beta (beta 5 I think) and verified that Resumable.js is working as expected. I wonder if this is related to a specific file, or is there's any other information that you can give to shine a light on the issue?

Steffen

**Comment by Marthyn** [comment]
Hi @steffentchr 

It happened with the feature that you can upload multiple files at once. It was with beta 3 i think, so maybe it is fixed now, will try again.

**Comment by Marthyn** [comment]
@steffentchr We tested again with beta 4, it works indeed again in Safari. Chrome is still an issue. Did you test in Chrome too?

**Comment by steffentchr** [comment]
No, didn't set that in the initial report - in guessing this is Chrome for iOS?



Steffen Fagerström Christensen
CTO & Co-founder, TwentyThree ™





+45 2532 7058 [tel:004525327058]
steffen@twentythree.net [steffen@twentythree.net]

TwentyThree™. The Video Marketing Platform.
twentythree.net [http://twentythree.net/]


On tir., okt. 25, 2016 at 7:34 AM, Marthyn Olthof <notifications@github.com> wrote:
@steffentchr [https://github.com/steffentchr] We tested again with beta 4, it works indeed again in Safari. Chrome is still an issue. Did you test in Chrome too?

**Comment by Marthyn** [comment]
@steffentchr Yes so the issue used to be

iOS beta 10.1 beta 3
Chrome iOS upload does not work.
Safari iOS upload does not work.

Now the issue is 

iOS beta 10.1 beta 4
Chrome iOS upload does not work.
Safari iOS upload DOES work.

So it seems there's just an issue with the beta ad chrome now.

**Comment by steffentchr** [comment]
Keeping this open until a GM of 10.1 -- to see how it shakes out.
