### ISSUE TITLE
two sessions uploading same file

### ISSUE THREAD

**Issue by prajwalmr62** [23/resumable.js#339]
As UniqueIdentifier is created by filesize and name, whenever two users upload same file, it corrupts both uploads and creates multiple files in output directory.

**Comment by steffentchr** [comment]
This seems like a problem wit the server-side implementation -- because uploading the exact same chunk twice for the same file shouldn't cause an issues; and two clients uploading the same file, with the same token should actually improve performance.

**Comment by prajwalmr62** [comment]
I'm deleting the temp files once the upload is complete. This causes an issue because file.1 gets deleted as soon as first upload is complete, thus making file.1 unavailable for second client.

**Comment by steffentchr** [comment]
Yeah, so that's probably the problem then, but that's mainly about then sharding the upload folder per user -- or allowing for simultaneous file uploads. We use the latter to great effect at TwentyThree, but the former may be a better option.
