### ISSUE TITLE
asynchronously handle unique identifier generation

### ISSUE THREAD

**Issue by thewilli** [23/resumable.js#341]
Hi,

it is currently [possible](https://github.com/23/resumable.js/blob/4f6b3d1ea4184d5963ba2f66b02b8edbc5f730bd/resumable.js#L350-L357) to pass a *pseudo-promise* (object wich provides a `done` and a `fail` method) as generator function to the `generateUniqueIdentifier` option. This is quite handy for me as I need to generate them (asynchronously) on the server side.

For my use case I'd like to

* rename `done` to `then` and `fail` to `catch`, in order to support regular ES6 Promises (without adding a direct dependency to them). This shouldn't brake anything as they are [not referenced](https://github.com/23/resumable.js/search?l=JavaScript&q=done&utf8=%E2%9C%93) anywhere and not documented anywhere
* Remove the invalid [addFile() invocation without any parameter](https://github.com/23/resumable.js/blob/4f6b3d1ea4184d5963ba2f66b02b8edbc5f730bd/resumable.js#L356) in case the `fail`callback is invoked. The file should be ignored in this case.
* Fire `filesAdded` **after** all unique ids are resolved, not matter if it happened asynchronously or not. In order to maintain IE compatibility I would do it without requiring Promise support (even though `Promise.all` would be quite handy here).
* Mention the extended `generateUniqueIdentifier` in the Readme.

Would you accept a Pull Request for the above things?

**Comment by steffentchr** [comment]
@thewilli Yup, that sounds well-reasoned and very valuable. Happy to accept the pr.
