### ISSUE TITLE
List jQuery as dependency

### ISSUE THREAD

**Issue by sjelfull** [23/resumable.js#344]
I think a note should be added that list jQuery as a dependency.

**Comment by znap026** [comment]
Why has it become a dependency? it wasn't needed before. I'm trying to work out what requires it?

**Comment by sjelfull** [comment]
I don't know anything about the history, but it obviously required?

https://github.com/23/resumable.js/blob/master/resumable.js#L12

**Comment by steffentchr** [comment]
This is on me for missing this in the [original PR](https://github.com/23/resumable.js/commit/6856014557ce8a9a56002c9ef6b8f0392d6a91e5) that introduced this.

@thewilli you introduced this check, but no other references to jQuery apart from this?

**Comment by Arood** [comment]
This is hilarious. Not only does it not use jQuery, but Resumable seems to use $ for it's own thing https://github.com/23/resumable.js/blob/master/resumable.js#L39

**Comment by znap026** [comment]
Exactly why was this added?

**Comment by steffentchr** [comment]
Pinging @thewilli again -- otherwise planning to remove it over the weekend.

**Comment by shabushabu** [comment]
Any news on this?

**Comment by shabushabu** [comment]
Cheers!

**Comment by thewilli** [comment]
sorry, I had some private, project-related content included when creating the MR
