### ISSUE TITLE
Problems with 401

### ISSUE THREAD

**Issue by jegjessing** [23/resumable.js#354]
If I use Resumable and the requests are done without authentication it just runs in an endless loop :-(
I would like for it to halt on response 401. I have tried to do console.log(message) on error and on fileError but that value is just undefined.

So any idea on how to solve this, or is this a bug in Resumable?

**Comment by steffentchr** [comment]
You can add `401` to the list of `permanentErrors` status codes when loading Resumable. Should do the trick ;)
