### ISSUE TITLE
Infinitely retrying ERR_CONNECTION_REFUSED without any event triggered

### ISSUE THREAD

**Issue by hyperknot** [23/resumable.js#356]
It seems that resumable.js (master) is not handling connection errors right. 

If my server is down:
- it tries to infinitely retry uploading all chunks
- it doesn't trigger any of: `fileRetry`, `fileError`, or `error`

So there is absolutely no way to check for this and stop the upload and display an error message. It just goes on without anything visible trying to make thousands of requests.

**Comment by steffentchr** [comment]
Yes, absolutely right -- or rather it's a consequence of `maxChunkRetries` being set to `undefined` by default, which in effect means that there's never an error occuring/registering. I've changed the default value to `100` to avoid this case.

**Comment by hyperknot** [comment]
But still, shouldn't fileRetry-s be fired?

**Comment by steffentchr** [comment]
They should -- and from what I can see they are?
<img width="1062" alt="screen shot 2017-01-16 at 01 40 13" src="https://cloud.githubusercontent.com/assets/16313/21967745/d29b6ae0-db8c-11e6-824e-641174a0f722.png">

**Comment by hyperknot** [comment]
In the master version from which I opened the ticket there were not fired.
