### ISSUE TITLE
Not supported file mask

### ISSUE THREAD

**Issue by vitiaaap29** [23/resumable.js#357]
I want to specify mask of files, which can be available to add.  'fileType' doesn't filter files (it's only alert, when I add file, which doesn't contain in fileType array.

**Comment by cpnielsen** [comment]
The code currently skips files that does not have the expected file extension, as seen here: https://github.com/23/resumable.js/blob/master/resumable.js#L364-L367

As such, it **does** work as a file _extension_ mask. Make sure you pass an array of file extensions (without the dot), such as `["pdf","gif","jpg", "jpeg"]`.

The default implementation of `fileTypeErrorCallback` simply outputs a warning that the file is not valid, which you can overwrite with your own implementation (to give visual feedback, cancel the upload, etc.)
