### ISSUE TITLE
Why testChunks request sends before first chunk request ?

### ISSUE THREAD

**Issue by Larryun** [23/resumable.js#361]
&ensp;&ensp;Am I using it in the wrong way or there is something that I don't know?Logically, the first chunk should send before the testChunks, in order to verify the previous chunk is received probably or not,
but now, the first testChunks request is used to determine whether the client should send the next chunk by responding with status code(404 means send next chunk, 200 means don't send).
&ensp;&ensp;Thanks for pointing out my faults.

**Comment by steffentchr** [comment]
@Larryun I might be misunderstanding the question, but ahead of every chunk being POST'ed to the server, there's a preflight/test GET request using the same information. So by that logic, tests are run before the actual data is sent.
