### ISSUE TITLE
upload after pause, one chunk is missing at server side

### ISSUE THREAD

**Issue by delr** [23/resumable.js#363]
Hi,

I have a issue, not sure if I did it wrong, or something wrong with resumable.js.

I pause the upload, then call "upload" to continue the upload.

For the chunk being paused/uploaded, the preprocessState is already 2, and when continue uploading, this chunk will not be sent again. But the server has not received the complete chunk yet, so it will be missing on the server side.

```javascript
  // Now, simply look for the next, best thing to upload
      $h.each($.files, function(file){
        if(file.isPaused()===false){
         $h.each(file.chunks, function(chunk){
           if(chunk.status()=='pending' && chunk.preprocessState === 0) {
             chunk.send();
             found = true;
             return(false);
           }
          });
        }
        if(found) return(false);
      });
```

If I delete the `chunk.preprocessState === 0`, the behavior looks correct.

Am I doing something wrong?

Thank you!

**Comment by niklr** [comment]
I had excatly the same issue and came to the same conclusion. Instead of deleting the `chunk.preprocessState === 0` check entirely it could be replaced with `chunk.preprocessState !== 1` because the chunk should not be sent while preprocessing.
