### ISSUE TITLE
Allow for object-storage-specific chunking?

### ISSUE THREAD

**Issue by Salketer** [23/resumable.js#364]
Hello, 

This module seems awesome. The only big problem I see for me is that I cannot use it to upload to my OpenStack Swift... Even if both Swift and Resumable.JS share all the principles to make it work it would require tweaks. Basically, it needs to use a different address for the GET request because, unless the storage is open to everyone, the request needs a signature forged by a server with correct access.

Here is the info for OpenStack https://docs.openstack.org/developer/swift/overview_large_objects.html
I am pretty certain it would also be useful if we could do the same thing for S3 and friends...

I would be happy to help define/develop this feature if you find it suitable for this exact module. Maybe it would be better to make it a different tool that would use resumable's API behind the scenes?

Thanks for your input.

**Comment by steffentchr** [comment]
There has been a few requests about this before -- and the consensus has been that even if it's an awesome feature, it's a feature that's out of scope for this library. It would be us building (and supporting!) interaction with services that we don't use ourselves.

**Comment by Salketer** [comment]
I understand, thank you for the fast feedback.

2017-02-23 18:45 GMT+01:00 Steffen Tiedemann Christensen <
notifications@github.com>:

**Comment by drzraf** [comment]
Did any developments arose since then within resumable.js?
@Salketer : Did you encountered a convenient alternative?

**Comment by arjan-s** [comment]
@drzraf I migrated to https://github.com/flowjs/flow.js which is an actively maintained alternative
