### ISSUE TITLE
resumable.js posting enclosing form instead of uploading to target url

### ISSUE THREAD

**Issue by zotlabs** [23/resumable.js#371]
Probably user error and not a bug but I'm having trouble with this. I've got an existing form and I'm migrating the 'upload' button from that form to resumable.js from Valum's qqUploader which is getting a bit dated. 

It seems like a straightforward process and I've attached resumable to the 'upload file' button with the assignBrowse function and removed the old bindings. The issue I'm having is that the target URL isn't getting called. Instead the enclosing form (to a different URL) is being submitted.  I could move the button outside the form but it's in a row of action buttons and this would screw up the legacy UI.

I can also easily add a 'preventDefault' action to the button, but if I do this the assignBrowse action tied to that button doesn't get called and I can't select a file.  

So I have something resembling the following:

    <form action="foo" method="post">
    ....other form elements

    <button id="upload_file">upload</button>

    ...other form elements
    <input type="submit" .... >
    </form>

       var r = new Resumable({
            target: '/upload',
            withCredentials: true
        });
        r.assignBrowse(document.getElementById('upload_file'));
        // the following line doesn't seem to make a difference, even if I add 'return false;' to the function.
        // without it, the same behaviour occurs 
        r.on('fileAdded', function(file, event) { r.upload(); });

If I click the button I can select a file. But once selected the surrounding form is submitted to endpoint 'foo' and a logging statement on endpoint /upload logs nothing - it isn't being touched. This isn't super-critical but if resumable.js folks have any ideas I'm willing to entertain them.

**Comment by steffentchr** [comment]
Yeah, if you have Resumable nested within a form, that form logic will apply to the form elements created by Resumable. In some cases this can be used to create features; although the usual advise is not to have Resumable within a form.
