### ISSUE TITLE
upload blob data in memory

### ISSUE THREAD

**Issue by afukada** [23/resumable.js#375]
I really like resumable.js so far! My initial testing has gone well.
I'm recording audio into memory as blob data, and want to upload it from memory instead of from a file. What approach would you suggest that I take? Any advice would be very much appreciated!

**Comment by cpnielsen** [comment]
You should be able to turn your blob into a File-object (in modern browsers):

`var fileOfBlob = new File([blob], 'aFileName.whatever');`

Once that is done and we assume you have initiated resumable into the variable `res`, you can add it directly as a file list:

`res.loadFiles([fileOfBlob])`

I haven't tested this, but something like this should work. Ofcourse, if you have multiple blobs you can add them simultaneously (`loadFiles` takes a list of File objects).

**Comment by afukada** [comment]
Wow, a great suggestion! I'll give it a try and report back. Thanks a lot!

**Comment by afukada** [comment]
I have the following test script, but am getting "resm.loadFiles is not a function." What am I doing wrong?

```
<script src="resumable.js"></script>
<script>
    var resm = new Resumable({
        target: 'resumable.php',
        testChunks: false
    });

resm.on('fileSuccess', function(file){
    console.debug('fileSuccess',file);
  });
.
.
.
resm.on('cancel', function(){
    console.debug('cancel');
  });

var data=[];
data.push('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
data.push('abcdefghijklmnopqrstuvwxyz');
data.push('1234567890');

var f;
for(var i=0; i<data.length; i++) {
	f = new File([data[i]],'f'+i.toString()+'.txt');
	resm.loadFiles(f);
}

```

**Comment by allansli** [comment]
@cpnielsen I think `loadFiles(items, event)` function is not exposed in resumable object.

**Comment by cpnielsen** [comment]
@allansli I think you might be right, it was me being a bit too tast.

@afukada There is an `addFile` function (https://github.com/23/resumable.js/blob/master/resumable.js#L1019-L1021), that you can use instead. It takes a single file at a time, but otherwise works the same.

**Comment by afukada** [comment]
Worked like a charm!
Thanks a lot!
