### ISSUE TITLE
what is the 'simultaneousUploads' mains? 

### ISSUE THREAD

**Issue by Borkes** [23/resumable.js#377]
![ljvc9oo0iqftjzcjfvd4va](https://cloud.githubusercontent.com/assets/20042707/25882046/31b8f002-3573-11e7-9c0c-8351bad2ce73.png)
simultaneousUploads default is 3, or I just set the value 4, but it does not start simultaneous upload of 4 files. 
![xnx42xqvxt3iddig6fqmaq](https://cloud.githubusercontent.com/assets/20042707/25882048/3332ca66-3573-11e7-8b6d-7bd3bf315227.png)
Acctually, it works one by one, if 'simultaneousUploads' mains the number of chuncks upload simultaneous, what should I do that I can start 4 files upload at a time

**Comment by cpnielsen** [comment]
The `simultaneousUploads` refers to how many parallel uploads are happening, but in terms of chunks, not files. The default, 3, means we will attempt to upload 3 chunks at a time, but all chunks from a single file will be uploaded before the next file is attempted.

If you want to do 4 files at a time, the easiest way is to start create 4 resumable instances and upload a file with each.
