### ISSUE TITLE
How to get resumable to start over

### ISSUE THREAD

**Issue by afukada** [23/resumable.js#386]
In my application, I have a number of post-processing things to do with a file after it's been uploaded. Those things are in the server-side PHP script because if any of them fails, I want to start over the uploading.

I thought sending 404 will trigger file upload again, but I'm getting an error event. What do I do to get resumable to start over the uploading?

**Comment by steffentchr** [comment]
@afukada The mode for Resumable is to deliver chunks for files successfully, and if any of the chunks fail either retry that chunk or ultimately fail the upload. 

A common pattern, for example, is to run verifications on parts coming in to the server side. And then void the entire upload if the verifications fail. 

In your case however, you're looking for the entire upload to reboot -- which isn't a built-in behaviour. You can do it easily enough though by listening to the `error` event handler and retriggering the upload.
