### ISSUE TITLE
Anyway to retrieve response headers?

### ISSUE THREAD

**Issue by ndaljr** [23/resumable.js#389]
I'm building a project which relies on receiving the response headers from an upload. Is there any way to get access to them?

**Comment by adamthedeveloper** [comment]
+1

**Comment by steffentchr** [comment]
The core idea of Resumable is to shoot of A LOT of requests for the same file -- and to make each of these chunk requests fairly disposable. If they fail, let's retry. Etc. 

This also means that there isn't a lot of utility built into the system around the chunks themselves. If you want to, however, you can find header through the `file` object that's being pushed in event. Specifically, `file.chunks` is an array of all file chunks; and each item in the array will have a `.xhr` property which should let you `.getAllResponseHeaders()` or whatever you need.
