### ISSUE TITLE
Upload finished, file.renameTo(new File(new_path)) failed.

### ISSUE THREAD

**Issue by shijiantian** [23/resumable.js#391]
Hello,
     when I try to resume upload,and call function checkIfUploadFinished( ), file.renameTo(new File(new_path)) return false. the temp file is open in java(TM) platform binary. 
     I found this bug when I try the java demo. I has closed RandomAccessFile and InputStream.
     Can anyone tell me how to solve this problem ?

**Comment by cpnielsen** [comment]
@shijiantian This is purely a backend issue and we cannot help you debug that. My suggestion is to split up the operations (create a new File, check if it is succesful, then try renaming, check again).

**Comment by shijiantian** [comment]
@cpnielsen Thank you for your reply.  Can you tell me what happened on the sever when I click on pause button on browser ? If the chunk is uploading when I click the pause button,can it finish the upload and close the RandomAccessFile? Or  it will pause on the server and never resume, when I click resume button on browser ,server will create a new progress/thread to upload the chunk.

**Comment by cpnielsen** [comment]
@shijiantian HTTP is stateless, so pressing pause during a chunk upload will cause the upload to stop, and resuming will cause a NEW chunk upload to occur.

If you never resume, nothing further happens.

**Comment by shijiantian** [comment]
So kind of you ,thank you very much.
