### ISSUE TITLE
How to get content file( or get hash) after add file.

### ISSUE THREAD

**Issue by pacificsoftdevld** [23/resumable.js#396]
Please tell me how to get content file( or get hash) after add file.
I want send md5 when upload file.
Thank advance.

**Comment by cpnielsen** [comment]
In the `fileAdded` event function, you can access the file object itself - the `file` parameter is an instance of `ResumableFile`:

```
r.on('fileAdded', function(file, event){
    var fileObject = file.file;
    var md5sum = <do something here>;
});
```

There is not a browser-native MD5 function (that I know of), but you can use something like [SparkMD5](https://github.com/satazor/js-spark-md5) to calculate it - check their documentation.

If you want to calculate / pass the MD5 value along with the request to the server for all chunks, you can also implement the MD5 calculation (and cache it) in a function you pass in as the `query` option when initiating Resumable:

```
function md5Query(file, chunk) {
    <Calculate MD5 hash of file, then cache it to avoid recalculating for each chunk>
}

var r = new Resumable({query: md5Query });
```
