### ISSUE TITLE
Documentation: assignBrowse does not work reliably with a button

### ISSUE THREAD

**Issue by tesujimath** [23/resumable.js#398]
As observed in #134, which alas got closed with no documentation update.

Some browsers don't like assignBrowse() being passed a button.  An easy work-around is to use a span, and style it like a button.

After spending a couple of days tracking down some weird behaviour here, I suggest documenting this.  On the home page.  Please!

(will you take a PR?)

**Comment by cpnielsen** [comment]
@tesujimath Good find. We'll be happy to accept a PR for the homepage / README. If you could expand on what browsers are affected (and what the underlying cause might be) that would be great :+1:
