### ISSUE TITLE
Restrict file type

### ISSUE THREAD

**Issue by Yamakaky** [23/resumable.js#401]
Is there a way to restrict the allowed filenames, like `*.mp3 *.ogg *.mkv`?

**Comment by steffentchr** [comment]
Yeah, use the `fileType` option when setting up Resumable.

**Comment by Yamakaky** [comment]
It's not on http://www.resumablejs.com/

**Comment by steffentchr** [comment]
Start with https://github.com/23/resumable.js/.

**Comment by Yamakaky** [comment]
Ok, thanks. It's outdated ?
