### ISSUE TITLE
Custom Alert when fileType is invalid.

### ISSUE THREAD

**Issue by pacificsoftdevld** [23/resumable.js#406]
Thanks for the amazing plugin. Everything works well.
But I am stuck in customing default alert when fileType is invalid.
Can anyone tell me how to solve it, please?
Thanks for any help!!!

**Comment by steffentchr** [comment]
You should be able to configure a property in your setup for Resumable for this one:

   var r = new Resumable({
     ....
     fileTypeErrorCallback: function(file, errorCount) {
        alert(file.fileName||file.name +' has type not allowed, please upload files of type ' + $.getOpt('fileType') + '.');
      }
    });

From here, simply change the behaviour -- whether by omitting the `alert()` entirely or by changing the text.

**Comment by pacificsoftdevld** [comment]
Thanks for your support.
It works well. :+1:
