### ISSUE TITLE
Can We add Metadata to Each Chunk

### ISSUE THREAD

**Issue by faraz-purelogics** [23/resumable.js#410]
Hi @steffentchr ,

Usually metadata found in only first chunk is there way that we can add metadata to each chunk?
Actually i want to re-encode or trans-code each chunk using FFMPEG and FFMPEG only accept first chunk and give error for other chunks as invalid input file may be first chunk has metadata and other chunks have not.

Thanks,
Faraz

**Comment by faraz-purelogics** [comment]
Hi @steffentchr / @bmaland / @jamescarlos / @2xyo / @Bantam ,

Can some one reply on this?

Thanks,
Faraz

**Comment by steffentchr** [comment]
Metadata in Resumable's sense is transferred through the request itself, not in the data of the file -- and that's part of every chunk request being sent off. For video transcoding and to transcode chunks individually you're out of Resumable's territory -- for that's you'd need to split into more logical chunks follow GOP structures, not just to split by size of the chunks.
