### ISSUE TITLE
Calling addFile() and upload() methods programmatically does not work

### ISSUE THREAD

**Issue by zachcowell** [23/resumable.js#414]
I have the below function

```javascript
function onUploadClick(files){
	const r = new Resumable({
		target: 'http://example.com/upload',
	});
	_.each(files, file => r.addFile(file))
	r.upload()
}
```

`files` is an array of `File` objects that I have access to via a React component. I have confirmed that the `addFile` method is creating the `ResumableFile` object. However, when I call the `upload` method, the XHR event does not fire. Am I missing anything in the configuration that would prevent the XHR from firing?

**Comment by zachcowell** [comment]
Here is a solution I ended up using to programmatically call the upload method. Basically, I just utilized the `fileAdded` event

```javascript	
static upload(files){
		const uploadEndpoint = `/upload`;
		const r = new Resumable({
			target: uploadEndpoint,
			simultaneousUploads : true,
			headers : {
				Authorization : Auth.getToken()
			}
		});
		if(!r.support) alert('Your browser does not support this feature'); //TODO: do better error handling
		r.on('fileSuccess', function(file){
			console.log('fileSuccess',file);
		});
		
		r.on('cancel', function(){
			console.log('cancel');
		});
		
		r.on('fileAdded', function(file, event){
			r.upload();
		});

		r.on('error', function(e){
			console.log('ERROR')
		})
		   

		_.each(files, file => r.addFile(file));
		return r;
	}
```

**Comment by mikemorton** [comment]
It's very strange that the API works this way.  Have the maintainers ever commented on why it is like this?
