### ISSUE TITLE
Question about the Java example - 

### ISSUE THREAD

**Issue by dgeswein-dlx** [23/resumable.js#424]
Why is the static class ResumableChunkNumber used in the HashSet in the ResumableInfo class.  Why not just use Integer class?  What properties of Integer class are not desirable - auto-boxing?

**Comment by cpnielsen** [comment]
@dgeswein-dlx The java example is not to be seen as best practice nor even a good example - it is included for "completeness" and community-provided.

In the specific case you are right that a simple integer would be faster, as intereger-comparison is not identity-based (like strings are) and hence there's no need for a special compare function.
