### ISSUE TITLE
Django Server side Setup with JQuery frontend working example

### ISSUE THREAD

**Issue by AlexXiong97** [23/resumable.js#426]
Would you please provide a simple working example on how to integrate **Resumable.js with Django Framework**?

Especially how to set up django controller(view functions) to accept chunked file upload.

Will be extremely helpful! Appreciate it!

**Comment by steffentchr** [comment]
Specific server-side implementation is slightly outside the scope of what w can help with in issues -- one hint though: Try [Googling "resumablejs django"](https://www.google.dk/search?q=resumablejs+django&ie=utf-8&oe=utf-8&client=firefox-b-ab&gws_rd=cr&dcr=0&ei=Tt4kWqWcOMfKsAfUq4GIBw).
