### ISSUE TITLE
Support for filetype validation custome error message

### ISSUE THREAD

**Issue by AlinCiocan** [23/resumable.js#438]
How can I add a custom error message for file type validation?

For example, I would like to accept only videos. Please see the image bellow:
![standard-message](https://user-images.githubusercontent.com/4248451/34995884-865c12fa-fae0-11e7-995c-5d75ccd17dbc.png)

And the message appears by default from resumable.js. I would like to have a custom error message, so I can add my translated message based on user's language.

An event like 'filetypenotsupported' it will be helpful in this scenario because I can handle this scenario in that handler.

**Comment by steffentchr** [comment]
Think you should be able to achieve this using the `fileTypeErrorCallback` property.

**Comment by AlinCiocan** [comment]
Thank you! And sorry for missing that event.
