### ISSUE TITLE
Parameter for max number of chunks uploaded simultaneously 

### ISSUE THREAD

**Issue by ADovgiy** [23/resumable.js#445]
Can you please add parameter, max number of chunks, it is for cases when we use **xhrTimeout** If user have low internet speed and xhrTimeout is set, when he upload multiple chunks simultaneously, bandwith of channel divided between all chunks so if resumablejs upload (for example) 3 chunks it can be uploaded in time of xhrTimeout but if it upload more we have lack of bandwidth, so they all will be cancelled and, should start uploading again

**Comment by steffentchr** [comment]
Is this different from the `simultaneousUploads` upload configuration option?

**Comment by ADovgiy** [comment]
Yes, simultaneousUploads  means number of simultaneous files uploads, and I'm asking for chunks.

**Comment by steffentchr** [comment]
`simultaneousUploads` is the number of processing running uploads; that's for chunks.
