### ISSUE TITLE
Drag and drop of a folder with more than 100 files uploads only 100 files.

### ISSUE THREAD

**Issue by Lehakos** [23/resumable.js#448]
**Steps to reproduce:**
1. Use Google Chrome
2. Drag and drop folder with more than 100 files within.

Only 100 files will be uploaded.

Resumable.js version: 1.1.0

**Comment by Lehakos** [comment]
I have created PR for this

**Comment by steffentchr** [comment]
Merged with thanks.

**Comment by vdiaza** [comment]
I am still seeing this issue, was it solved?
