### ISSUE TITLE
single page website - file options

### ISSUE THREAD

**Issue by JindrichPilar** [23/resumable.js#45]
In single page apps (with AngularJS for example) it is unhandy to create instance of resumable.js each time you want to assign different query to request.

Imagine implementing upload for file manager (kind of my case). How would you specify    path where to put the file? 

This way?

```
var root = new Resumable({
  target:'/api/upload', 
  query:{path: '/''}
});

var images = new Resumable({
  target:'/api/upload', 
  query:{path: '/images''}
});

var images-christmas = new Resumable({
  target:'/api/upload', 
  query:{path: '/'images/christmas'}
});

//and many, many others
```

So, i thought about posibility to specify options (why only query?) for files.

How the api may looks:

```
var root = new Resumable({
  target:'/api/upload', 
  query:{path: '/''}
});

root.setFileOptions( {
  query: {path: '/docs'}
});
//files added to resumable.js after setting this will use option specified by fileOptions

root.setFileOptions( {
  chunkSize: 512*1024
  query: {path: '/presentaion'}
});
//files added to resumable.js after setting this will use option specified by fileOptions

root.setFileOptions();
//files added to resumable.js after setting this will use instance option

```

e.g. In file manager when user opens folder, you just tell resumable the change with setFileOptions.

Any thoughts? Any other API proposals for this?

**Comment by Roisholto** [comment]
What I did in my case In  order to change parameters on the fly was to do something like this, 
R=resumable ({}) 
Then R. opts['query'] = {name="somevalue"} 
R. upload() 
I believe other Params can be manipulated before calling the upload method
