### ISSUE TITLE
XMLHttpRequest issue because no secure

### ISSUE THREAD

**Issue by pcata6** [23/resumable.js#460]
I have an issue (Mixed Content: The page at 'https://uploadxxxxx/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint), because the request is not secure.
I use nginx.
Somebody known this issue ?

**Comment by steffentchr** [comment]
Depends on your setup for Resumable, I guess -- but not a known issue.

**Comment by pcata6** [comment]
Ok thks, i will check my config
