### ISSUE TITLE
Query/Proposal  - start chunk number for resumed uploads

### ISSUE THREAD

**Issue by keepRunning** [23/resumable.js#468]
Can I mention a start chunk number to test/upload can resume from that chunk. 

Use case:
Upload of 30GB file. If I have 5MB chunks, it still gives me 6000 chunks. If I already have uploaded 95% and have to resume, the checking still has to start from 0%(5700 GET to test). This would be a lot of unnecessary  GET calls and unnecessary server work and IO to handle each request.

**Comment by steffentchr** [comment]
There's currently no way of doing this automatically -- although you'll likely easily be able to iterate through chunks to flag off "done" bits. I agree on the problem of the overhead; while on the other hand the asynchronicity is one of the core upsides of Resumable. Anyways, would receive a well-designed PR handling this case.
