### ISSUE TITLE
Large files take a considerable amount of time to reassemble, resulting in a "404 Not Found" being passed to the client.

### ISSUE THREAD

**Issue by techburgher** [23/resumable.js#473]
I'm not a real programmer, so there may be a way to account for this, but if I upload a "large" file, say 8GB, when the server-side script is reassembling the chunks, it fails to send the last HTTP/1.1 200 until after reassembly, which causes the client to display a 404 Not Found error, presumably due to the large delay. Is there a way to handle this?

```
DEBUG in resume [resume.py:36]:
Getting chunk: /uploads/8388608000-8g_test/8g_test_part_8000

[pid: 24896|app: 0|req: 50508/122821] 172.17.3.226 () {40 vars in 1113 bytes} [Mon Jun 25 17:40:44 2018] GET /resumable_upload?resumableChunkNumber=8000&resumableChunkSize=1048576&resumableCurrentChunkSize=1048576&resumableTotalSize=8388608000&resumableType=&resumableIdentifier=8388608000-8g_test&resumableFilename=8g_test&resumableRelativePath=8g_test&resumableTotalChunks=8000 => generated 121 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 72 bytes (1 switches on core 1)

DEBUG in resume [resume.py:49]:
POST called

DEBUG in resume [resume.py:74]:
Saved chunk: /uploads/8388608000-8g_test/8g_test_part_8000


** HUGE DELAY HERE **

DEBUG in resume [resume.py:92]:
File saved to: /uploads/8g_test

[pid: 24896|app: 0|req: 50509/122822] 172.17.3.226 () {46 vars in 1342 bytes} [Mon Jun 25 17:40:44 2018] POST /resumable_upload?resumableChunkNumber=8000&resumableChunkSize=1048576&resumableCurrentChunkSize=1048576&resumableTotalSize=8388608000&resumableType=&resumableIdentifier=8388608000-8g_test&resumableFilename=8g_test&resumableRelativePath=8g_test&resumableTotalChunks=8000 => generated 2 bytes in 76574 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 1)
```

**Comment by techburgher** [comment]
Well....I think I see the problem, but I'm testing again. One of the backend sample scripts does not return 'OK' until after processing all of the chunks:

```
    # combine all the chunks to create the final file
    if upload_complete:
        target_file_name = os.path.join(temp_base, resumableFilename)
        with open(target_file_name, "ab") as target_file:
            for p in chunk_paths:
                stored_chunk_file_name = p
                stored_chunk_file = open(stored_chunk_file_name, 'rb')
                target_file.write(stored_chunk_file.read())
                stored_chunk_file.close()
                os.unlink(stored_chunk_file_name)
        target_file.close()
        os.rmdir(temp_dir)
        app.logger.debug('File saved to: %s', target_file_name)

    return 'OK'
```

I'm guessing if I move that OK before the upload_complete block, all will be well.

**Comment by techburgher** [comment]
Moving the return 'OK' corrects the issue.

**Comment by techburgher** [comment]
So...yeah -- this is still an issue, but it's a problem with the server-side script and not the resumable.js script, per say. If I move the return 'OK' to above the upload_complete block, then it never processes the chunks...duh.

Suggestions on how to correct this?

**Comment by FabianElsmer** [comment]
We solved this, by moving the logic to reassemble (and upload again to an s3 Bucket) into its own task that gets executed by a worker process.
I don't think the library can do much about it, you could increase the timeouts to a lot higher values to at least avoid the error.

**Comment by rekado** [comment]
Reassembling should not be necessary when you write directly to the target file at the expected offset.  You can compute the offset by multiplying the chunk number by the chunk size.
