### ISSUE TITLE
Feature request: Add an option to define a class when dragging files over the drop zone

### ISSUE THREAD

**Issue by SuperPat45** [23/resumable.js#476]
Hi,

Currently, as shown in examples, if you want to add a class when dragging a file in the drop zone, you need to explicitly adding a code like;

```
<div class="resumable-drop" 
    ondragenter="jQuery(this).addClass('resumable-dragover');"
    ondragend="jQuery(this).removeClass('resumable-dragover');"
    ondrop="jQuery(this).removeClass('resumable-dragover');">
    Drop video files here to upload or <a class="resumable-browse"><u>select from your computer</u></a>
</div>
```

It would be preferable to have an option "dragoverClass" directly integrated into resumablejs?

**Comment by steffentchr** [comment]
Sounds like a pretty good idea -- if you want to contribute with a PR for this, I'll happily accept.
