### ISSUE TITLE
Generated identifier when dropping a folder on Chome and Edge does not contains the relativePath

### ISSUE THREAD

**Issue by SuperPat45** [23/resumable.js#489]
The generated identifier function when dropping a folder on Chome and Edge does not contains the relativePath:

If you want to upload a directory named img containing a file name image.png
When selecting this directory on every browser or when dropping this directory on firefox, the uniqueIdentifier is:
> 60949-imgimagepng

When dropping this directory on chrome/edge, the uniqueIdentifier is:
> 60949-imgimagepng

**Comment by steffentchr** [comment]
Merged with thanks ;)
