### ISSUE TITLE
Last chunk is bigger then configured chunkSize

### ISSUE THREAD

**Issue by sreuter** [23/resumable.js#51]
While enforcing the maximum chunkSize on a Server-Side (node.js) I realized that the last chunk is often bigger than the configured chunkSize. The source code states this is how it is supposed to be at https://github.com/23/resumable.js/blob/master/resumable.js#L259

Why are we doing this? And if there is a good reason for it, shouldn't we mention the behavior in the documentation?

**Comment by pacificsoftdevld** [comment]
Hi all. 
in ` r.on('fileAdded', (file, event) => {});`
I want get content to create md5 hash and add it into query of  this file.
Please help me get content file.

**Comment by cpnielsen** [comment]
@pacificsoftdevld Please don't hijack other issues with unrelated comments (I can see you also created an issue, which is the right approach).

**Comment by jago960** [comment]
Good, well educative to [read](https://mstwotoes.com/), Thank You
