### ISSUE TITLE
Dynamic query for each file.

### ISSUE THREAD

**Issue by TomasRezende** [23/resumable.js#517]
Hi, I'm trying to send a unique verification token for each file I upload.

Currently I'm passing the verification token on query parameter when I create Resumable instance 
(ex.: 
var r = new Resumable({
             target: '{{ target}}',
             query:{verification_token: '{{ token }}'},
             prioritizeFirstAndLastChunk: false,
             simultaneousUploads: 1, ...). 
The problem is that if multiple files are added, every file will have the same token.

Is there an easy way to set an individual token parameter on query for each file that will be sent?

Thanks ,
Tomas

**Comment by steffentchr** [comment]
Sure, you can have `{query:function(){...}}` and do whatever.
