### ISSUE TITLE
Porn link in the code

### ISSUE THREAD

**Issue by Luc45** [23/resumable.js#590]
Our CEO informed me there was a porn link in our codebase.

https://github.com/23/resumable.js/blob/master/resumable.js#L3

![MlHm0Zg](https://user-images.githubusercontent.com/9341686/121920703-ab2cac80-cd0e-11eb-9b59-7d86752c141f.gif)

**Comment by steffentchr** [comment]
@Luc45 Loved the gif! Agreed that the old links are not that helpful, even I managed to change my name along the way ;)

**Comment by Luc45** [comment]
Thanks for the quick fix!

Let me update the title of the issue to something more... subtle.
