### ISSUE TITLE
resumablejs.com down

### ISSUE THREAD

**Issue by mayeaux** [23/resumable.js#598]
https://resumablejs.com returns an nginx 502 error currently

**Comment by mayeaux** [comment]
Still down btw

**Comment by suraj-davariya** [comment]
https://resumablejs.com is still down! 👀  😞 
Redirecting to random websites, on each visit! 🪦

**Comment by Liziming726** [comment]
hi, website still returns 502 error, haven't repair? the key value should be from which to get ? thanks

**Comment by steffentchr** [comment]
Yeah, we didn't renew the domain -- since it was just a mirror of the readme here. I've also remove the link from the repo now 👍
