### ISSUE TITLE
429 Error - Too many requests - when uploading larger files.

### ISSUE THREAD

**Issue by xongooli** [23/resumable.js#600]
While smaller files below 50MB are loading successfully, I'm getting this 429 server error on larger files after about 400 chunks have uploaded.  The error aborts the upload process. 

I'm using vue.js

I understand this might be resolved through a header instruction though I'm not sure how to handle this,  or possibly increasing the chunk size?

Would appreciate any advice here.

**Comment by steffentchr** [comment]
@xongooli This seems server-related -- as in you need to look into why your server is pushing 429s to you.
