### ISSUE TITLE
internal server error in last chunk

### ISSUE THREAD

**Issue by MelikaSharafi** [23/resumable.js#608]
Hi, I have a file larger than 1 MB, when I upload one of the last chunks (usually the last chunk) it gives an error of 500 (inernal server error)

my config : 
let resumable = new Resumable({
                target: "{{route('user.upload')}}",
                query:{_token:"{{ csrf_token() }}",file_type: value.name} ,
                chunkSize: 1*1024*1024, // default is 1*1024*1024, this should be less than your maximum limit in php.ini
                // prioritizeFirstAndLastChunk: true,
                forceChunkSize: true,
                headers: {
                    'Accept' : 'application/json'
                },
                testChunks: false,
                throttleProgressCallbacks: 1,
            });

**Comment by MelikaSharafi** [comment]
The problem was not in this package :/

**Comment by 764653880** [comment]
> The problem was not in this package :/
