### ISSUE TITLE
Error occured when uploading to shared drive folder

### ISSUE THREAD

**Issue by mischro** [23/resumable.js#611]
Hello,

First of all I want to thank you for this great upload solution! :)

Everything is fine when using the api with a normal drive folder.

But if I want to upload to a folder in a shared drive or to a shared drive directly, I got an error message and the upload failed.

The console is always logging the following error messages:

_Uncaught (in promise) Error: Something is not right!
    at userCodeAppPanel:45:22
    at resumableupload_js.min.js:1:979
    at resumableupload_js.min.js:1:4082
(_

_Resumableupload_js.min.js:1     
PUT https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&upload_id=ADPycdsqloNJF9OmbuFCB6JpcD3htOdlh6DOMUNQvqomMx0NjoDZakwApaTOwktb4buKtQ6wJZZkRAEPFyI8leYEX4TC16btQrbx 404_

_additionalInformation: "When the file size is large, there is the case that the file cannot be converted to Google Docs. Please be careful this."
{message: 'File not found: 1PGWHPR9yDUq5k5sTyGba02ghXfSB-OrM.', domain: 'global', reason: 'notFound', location: 'fileId', locationType: 'parameter'}_

Note: _1PGWHPR9yDUq5k5sTyGba02ghXfSB-OrM_ is the folder id of the shared drive folder.

Do you have a solution for this?

Thanks in advance.

**Comment by steffentchr** [comment]
@mischro Resumable.js requires and backend that supports the upload patterns, and I'm pretty sure this is not the case for Google Drive.
