### ISSUE TITLE
Some doubt about resumable.js

### ISSUE THREAD

**Issue by frank-fan** [23/resumable.js#62]
I found that to work with Resumable.js, the `server side` should:
First, save all trunks to files like `file.trunk-1`, 'file.trunk-2'...; 
After all trunks received, the `server side` combines all trunk file to a single file to finish upload. 
I am extremely worried that this combination will consume a plenty of time which will slow down the file-upload progress.

Any idea to solve this problem?

**Comment by faller** [comment]
thanks @steffentchr , this help me a lot
"Finally, a number of reverse proxies (nginx, pound from my own experience) do not offer steaming uploads and instead buffers the entire request before forwarding it (again, a good motivation for node). In those cases, you'll have full data immediately upon request -- and the big file + seek approach is probably good."
